"""
רשימת תרופות מורחבת לשימוש במערכת מנהל האירוע הרפואי.
פורמט: (שם_מסחרי, שם_גנרי, צורת_מתן)
"""

# שם מסחרי (אנגלי) → שם עברי נפוץ / תעתיק עברי
HEBREW_NAMES: dict[str, str] = {
    # כאב / חום / אנטי-דלקתי
    "Acamol": "אקמול", "Paracetamol": "פרצטמול", "Optalgin": "אופטלגין",
    "Dipyrone": "דיפירון", "Ibufen": "איבופן", "Advil": "אדוויל",
    "Ibuprofen": "איבופרופן", "Voltaren": "וולטרן", "Diclofenac": "דיקלופנאק",
    "Arcoxia": "ארקוקסיה", "Etoricoxib": "אטוריקוקסיב",
    "Celebrex": "סלברקס", "Celecoxib": "צלקוקסיב",
    "Naproxen": "נפרוקסן", "Proxen": "פרוקסן",
    "Indocid": "אינדוסיד", "Indomethacin": "אינדומתצין",
    "Tramadex": "טרמדקס", "Tramadol": "טרמדול", "Ultram": "אולטרם",
    "Zaldiar": "זלדיאר",
    "Oxycontin": "אוקסיקונטין", "Oxycodone": "אוקסיקודון",
    "Norspan": "נורספן", "Buprenorphine": "בופרנורפין",
    "Fentanyl": "פנטניל", "Durogesic": "דורוג'זיק",
    "Morphine": "מורפין", "Sevredol": "סברדול",
    "MST Continus": "MST קונטינוס",
    "Lyrica": "ליריקה", "Pregabalin": "פרגבלין",
    "Neurontin": "נוירונטין", "Gabapentin": "גבפנטין",
    # לחץ דם — מעכבי ACE / ARB
    "Enalapril": "אנלפריל", "Ramipril": "רמיפריל", "Tritace": "טריטייס",
    "Lisinopril": "ליזינופריל", "Zestril": "זסטריל",
    "Perindopril": "פרינדופריל", "Coversyl": "קוברסיל",
    "Captopril": "קפטופריל",
    "Losartan": "לוסרטן", "Cozaar": "קוזאר",
    "Valsartan": "ולסרטן", "Diovan": "דיובן",
    "Irbesartan": "אירבסרטן", "Candesartan": "קנדסרטן",
    "Olmesartan": "אולמסרטן",
    # לחץ דם — חוסמי בטא
    "Concor": "קונקור", "Bisoprolol": "ביסופרולול",
    "Betaloc": "בטאלוק", "Metoprolol": "מטופרולול",
    "Atenolol": "אטנולול", "Carvedilol": "קארוודילול", "Coreg": "קורג",
    "Propranolol": "פרופרנולול",
    # לחץ דם — חוסמי סידן
    "Norvasc": "נורוואסק", "Amlopin": "אמלופין", "Amlodipine": "אמלודיפין",
    "Felodipine": "פלודיפין", "Nifedipine": "ניפדיפין",
    "Verapamil": "ורפמיל", "Diltiazem": "דילטיאזם",
    "Doxazosin": "דוקסאזוסין",
    "Moxonidine": "מוקסונידין", "Clonidine": "קלונידין",
    "Methyldopa": "מתילדופה", "Hydralazine": "הידרלזין",
    "Nitroglycerin": "ניטרוגליצרין", "Isorind": "איזורינד",
    # אי ספיקת לב / הפרעות קצב
    "Digoxin": "דיגוקסין", "Lanoxin": "לנוקסין",
    "Amiodarone": "אמיודרון", "Cordarone": "קורדרון",
    "Entresto": "אנטרסטו", "Inspra": "אינספרה",
    "Veroshpiron": "ורושפירון",
    "Ivabradine": "איוברדין", "Procoralan": "פרוקורלן",
    "Sotalol": "סוטלול", "Flecainide": "פלקאינייד", "Tambocor": "טמבוקור",
    "Propafenone": "פרופאפנון",
    # משתנים
    "Lasix": "לאסיקס", "Furosemide": "פורוסמיד",
    "Aldactone": "אלדקטון", "Spironolactone": "ספירונולקטון",
    "Moduretic": "מודורטיק", "Hydrochlorothiazide": "הידרוכלורותיאזיד",
    "Indapamide": "אינדאפמיד", "Torsemide": "טורסמיד",
    "Bumetanide": "בומטניד",
    # נוגדי קרישה
    "Aspirin Cardio": "אספירין קרדיו", "Aspirin": "אספירין",
    "Plavix": "פלביקס", "Clopidogrel": "קלופידוגרל",
    "Brilique": "ברילינטה", "Ticagrelor": "טיקגרלור",
    "Prasugrel": "פרסוגרל", "Effient": "אפיינט",
    "Coumadin": "קומדין", "Warfarin": "וורפרין",
    "Xarelto": "קסרלטו", "Rivaroxaban": "ריברוקסבן",
    "Eliquis": "אליקויס", "Apixaban": "אפיקסבן",
    "Pradaxa": "פרדקסה", "Dabigatran": "דביגטרן",
    "Lixiana": "ליקסיאנה", "Edoxaban": "אדוקסבן",
    "Heparin": "הפרין", "Clexane": "קלקסיין", "Enoxaparin": "אנוקספרין",
    "Fragmin": "פרגמין", "Dalteparin": "דלטפרין",
    "Innohep": "אינוהפ", "Tinzaparin": "טינזפרין",
    "Dipyridamole": "דיפירידמול", "Persantin": "פרסנטין",
    # כולסטרול
    "Lipitor": "ליפיטור", "Atorvastatin": "אטורווסטטין",
    "Crestor": "קרסטור", "Rosuvastatin": "רוסובסטטין",
    "Zocor": "זוקור", "Simvastatin": "סימוסטטין",
    "Pravastatin": "פרווסטטין", "Fluvastatin": "פלובסטטין",
    "Pitavastatin": "פיטוסטטין",
    "Ezetimibe": "אזטימיב", "Ezetrol": "אזטרול",
    "Inegy": "אינגי", "Repatha": "רפטה", "Praluent": "פרולנט",
    "Evolocumab": "אוולוקומב", "Alirocumab": "אלירוקומב",
    "Fenofibrate": "פנופיברט", "Lipanthyl": "ליפנטיל",
    "Gemfibrozil": "ג'מפיברוזיל",
    "Omega-3": "אומגה 3", "Omacor": "אומקור",
    # סוכרת
    "Glucophage": "גלוקופאג'", "Metformin": "מטפורמין",
    "Januvia": "ג'נוויה", "Sitagliptin": "סיטגליפטין",
    "Trajenta": "טרג'נטה", "Linagliptin": "לינגליפטין",
    "Galvus": "גלבוס", "Vildagliptin": "וילדגליפטין",
    "Onglyza": "אונגליזה", "Saxagliptin": "סקסגליפטין",
    "Jardiance": "ג'ארדיאנס", "Empagliflozin": "אמפגליפלוזין",
    "Forxiga": "פורקסיגה", "Dapagliflozin": "דפגליפלוזין",
    "Invokana": "אינווקנה", "Canagliflozin": "קנגליפלוזין",
    "Ozempic": "אוזמפיק", "Semaglutide": "סמגלוטיד",
    "Rybelsus": "ריבלסוס", "Victoza": "ויקטוזה", "Liraglutide": "לירגלוטיד",
    "Trulicity": "טרוליסיטי", "Dulaglutide": "דולגלוטיד",
    "Byetta": "ביאטה", "Exenatide": "אקסנטיד",
    "Toujeo": "טוג'יאו", "Lantus": "לנטוס", "Basaglar": "בסגלר",
    "Tresiba": "טרסיבה", "Insulin Degludec": "אינסולין דגלודק",
    "Levemir": "לבמיר", "Insulin Detemir": "אינסולין דטמיר",
    "Novorapid": "נוברפיד", "Insulin Aspart": "אינסולין אספרט",
    "Humalog": "הומלוג", "Insulin Lispro": "אינסולין ליספרו",
    "Apidra": "אפידרה", "Insulin Glulisine": "אינסולין גלוליזין",
    "Humulin R": "הומולין R", "Humulin N": "הומולין N",
    "Mixtard": "מיקסטרד",
    "Amaryl": "אמריל", "Glimepiride": "גלימפיריד",
    "Glipizide": "גליפיזיד", "Gliclazide": "גליקלזיד",
    "Pioglitazone": "פיוגליטזון", "Acarbose": "אקרבוז",
    "Repaglinide": "רפגלינייד",
    # בלוטת תריס
    "Eltroxin": "אלטרוקסין", "Euthyrox": "אוטירוקס",
    "Levothyroxine": "לבותירוקסין", "Synthroid": "סינתרויד",
    "Propylthiouracil": "פרופילתיאורציל", "Carbimazole": "קרבימזול",
    # אפילפסיה
    "Tegretol": "טגרטול", "Carbamazepine": "קרבמזפין",
    "Depakine": "דפאקין", "Valproic Acid": "חומצה ולפרואית",
    "Lamictal": "לאמיקטל", "Lamotrigine": "למוטריג'ין",
    "Keppra": "קפרה", "Levetiracetam": "לבטירצטם",
    "Topamax": "טופמקס", "Topiramate": "טופירמט",
    "Phenobarbital": "פנוברביטל", "Luminal": "לומינל",
    "Phenytoin": "פניטואין", "Dilantin": "דילנטין",
    "Oxcarbazepine": "אוקסקרבזפין", "Trileptal": "טרילפטל",
    "Briviact": "בריויאקט", "Brivaracetam": "ברירצטם",
    "Vimpat": "וימפט", "Lacosamide": "לקוסמיד",
    "Fycompa": "פיקומפה", "Perampanel": "פרמפנל",
    "Epidyolex": "אפידיולקס", "Cannabidiol": "קנביידיול",
    "Rivotril": "ריבוטריל", "Clonazepam": "קלונזפם",
    # פרקינסון
    "Madopar": "מאדופר", "Sinemet": "סינמט",
    "Levodopa": "לבודופה", "Stalevo": "סטלבו",
    "Requip": "רקוויפ", "Ropinirole": "רופינירול",
    "Mirapex": "מירפקס", "Pramipexole": "פרמיפקסול",
    "Neupro": "נויפרו", "Rotigotine": "רוטיגוטין",
    "Azilect": "אזילקט", "Rasagiline": "רסגילין",
    "Selegiline": "סלג'ילין", "Comtan": "קומטן",
    "Entacapone": "אנטקפון", "Tasmar": "טסמר",
    "Amantadine": "אמנטדין",
    # טרשת נפוצה (MS)
    "Copaxone": "קופקסון", "Glatiramer Acetate": "גלטירמר אצטט",
    "Avonex": "אבונקס", "Rebif": "רביף", "Betaferon": "בטאפרון",
    "Extavia": "אקסטביה",
    "Tecfidera": "טקפידרה", "Dimethyl Fumarate": "דימתיל פומרט",
    "Aubagio": "אובג'יו", "Teriflunomide": "טריפלונומיד",
    "Gilenya": "ג'ילניה", "Fingolimod": "פינגולימוד",
    "Mayzent": "מייזנט", "Siponimod": "ספונימוד",
    "Kesimpta": "קסימפטה", "Ofatumumab": "אופטומומב",
    "Ocrevus": "אוקרבוס", "Ocrelizumab": "אוקרליזומב",
    "Tysabri": "טיסברי", "Natalizumab": "נטליזומב",
    "Lemtrada": "למטרדה", "Alemtuzumab": "אלמטוזומב",
    "Ponvory": "פונבורי", "Zeposia": "זפוסיה",
    # דמנציה
    "Aricept": "אריספט", "Donepezil": "דונפזיל",
    "Exelon": "אקסלון", "Rivastigmine": "ריבסטיגמין",
    "Reminyl": "רמיניל", "Galantamine": "גלנטמין",
    "Ebixa": "אביקסה", "Memantine": "ממנטין",
    # דיכאון / חרדה
    "Cipralex": "ציפרלקס", "Escitalopram": "אסציטלופרם",
    "Prozac": "פרוזק", "Fluoxetine": "פלואוקסטין",
    "Zoloft": "זולופט", "Sertraline": "סרטרלין",
    "Effexor": "אפקסור", "Venlafaxine": "ונלפקסין",
    "Cymbalta": "סימבלטה", "Duloxetine": "דולוקסטין",
    "Remeron": "רמרון", "Mirtazapine": "מירטזפין",
    "Paroxetine": "פרוקסטין", "Citalopram": "ציטלופרם",
    "Fluvoxamine": "פלובוקסמין",
    "Anafranil": "אנפרניל", "Clomipramine": "קלומיפרמין",
    "Amitriptyline": "אמיטריפטילין", "Nortriptyline": "נורטריפטילין",
    "Bupropion": "בופרופיון", "Wellbutrin": "ולבוטרין",
    "Valdoxan": "ולדוקסן", "Agomelatine": "אגומלטין",
    "Xanax": "קסנקס", "Alprazolam": "אלפרזולם",
    "Valium": "וליום", "Diazepam": "דיאזפם",
    "Lorazepam": "לורזפם", "Lorivan": "לוריבן",
    "Buspirone": "בוספירון", "Stilnox": "סטילנוקס", "Zolpidem": "זולפידם",
    "Imovane": "אימובן", "Zopiclone": "זופיקלון",
    # אנטי-פסיכוטיים / מייצבי מצב רוח
    "Risperdal": "ריספרדל", "Risperidone": "ריספרידון",
    "Zyprexa": "זיפרקסה", "Olanzapine": "אולנזפין",
    "Seroquel": "סרוקוול", "Quetiapine": "קוויטיאפין",
    "Abilify": "אביליפיי", "Aripiprazole": "אריפיפרזול",
    "Clozaril": "קלוזריל", "Clozapine": "קלוזפין",
    "Haldol": "הלדול", "Haloperidol": "הלופרידול",
    "Amisulpride": "אמיסולפריד",
    "Lithium": "ליתיום", "Camcolit": "קמקוליט",
    "Depakote": "דפקוט",
    # ADHD
    "Ritalin": "ריטאלין", "Methylphenidate": "מתילפנידט",
    "Concerta": "קונצרטה", "Medikinet": "מדיקינט",
    "Adderall": "אדרול",
    "Strattera": "סטרטרה", "Atomoxetine": "אטומוקסטין",
    "Intuniv": "אינטוניב",
    # אונקולוגיה — כימותרפיה
    "Cyclophosphamide": "ציקלופוספמיד",
    "Methotrexate": "מתוטרקסט",
    "Fluorouracil": "פלואורואורציל (5-FU)",
    "Capecitabine": "קפציטבין", "Xeloda": "קסלודה",
    "Doxorubicin": "דוקסורוביצין", "Adriamycin": "אדריאמיצין",
    "Epirubicin": "אפירוביצין",
    "Paclitaxel": "פקליטקסל", "Taxol": "טקסול",
    "Docetaxel": "דוצטקסל", "Taxotere": "טקסוטר",
    "Carboplatin": "קרבופלטין", "Cisplatin": "ציספלטין",
    "Oxaliplatin": "אוקסליפלטין", "Eloxatin": "אלוקסטין",
    "Gemcitabine": "ג'מציטבין", "Gemzar": "ג'מזר",
    "Vinorelbine": "וינורלבין",
    "Irinotecan": "אירינוטקן", "Etoposide": "אטופוסייד",
    "Pemetrexed": "פמטרקסד", "Alimta": "אלימטה",
    "Melphalan": "מלפלן", "Chlorambucil": "כלורמבוציל",
    "Bleomycin": "בלאומיצין", "Vincristine": "וינקריסטין",
    "Cytarabine": "ציטרבין", "Dacarbazine": "דקרבזין",
    "Temozolomide": "טמוזולומיד", "Temodal": "טמודל",
    "Hydroxyurea": "הידרוקסיאוריאה",
    # אונקולוגיה — טיפול ממוקד
    "Herceptin": "הרספטין", "Trastuzumab": "טרסטוזומב",
    "Kadcyla": "קדסילה", "Enhertu": "אנהרטו",
    "Perjeta": "פרג'טה", "Pertuzumab": "פרטוזומב",
    "Avastin": "אוואסטין", "Bevacizumab": "בוציזומב",
    "Erbitux": "ארביטוקס", "Cetuximab": "צטוקסימב",
    "Vectibix": "וקטיביקס",
    "Gleevec": "גליבק", "Imatinib": "אימטיניב",
    "Tasigna": "טסיניה", "Nilotinib": "נילוטיניב",
    "Sprycel": "ספריסל", "Dasatinib": "דסטיניב",
    "Bosulif": "בוסוליף", "Iclusig": "איקלוסיג",
    "Tarceva": "טרסבה", "Erlotinib": "ארלוטיניב",
    "Iressa": "אירסה", "Gefitinib": "ג'פיטיניב",
    "Gilotrif": "ג'ילוטריף", "Afatinib": "אפטיניב",
    "Tagrisso": "טגריסו", "Osimertinib": "אוסימרטיניב",
    "Xalkori": "זלקורי", "Crizotinib": "קריזוטיניב",
    "Alecensa": "אלסנסה", "Alectinib": "אלקטיניב",
    "Lorbrena": "לורברנה", "Lorlatinib": "לורלטיניב",
    "Zelboraf": "זלבורף", "Vemurafenib": "וומורפניב",
    "Tafinlar": "טפינלר", "Dabrafenib": "דברפניב",
    "Mekinist": "מקיניסט", "Trametinib": "טרמטיניב",
    "Ibrance": "איברנס", "Palbociclib": "פלבוציקליב",
    "Kisqali": "קיסקלי", "Ribociclib": "ריבוציקליב",
    "Verzenio": "ורזניו", "Abemaciclib": "אבמציקליב",
    "Lynparza": "לינפרזה", "Olaparib": "אולפריב",
    "Zejula": "זג'ולה", "Niraparib": "נירפריב",
    "Imbruvica": "אימברוויקה", "Ibrutinib": "איברוטיניב",
    "Calquence": "קלקוונס", "Acalabrutinib": "אקלברוטיניב",
    "Brukinsa": "ברוקינסה", "Zanubrutinib": "זנוברוטיניב",
    "Venclexta": "וונקלקסטה", "Venetoclax": "ונטוקלקס",
    "Zytiga": "זיטיגה", "Abiraterone": "אבירטרון",
    "Xtandi": "אקסטנדי", "Enzalutamide": "אנזלוטמיד",
    "Nubeqa": "נובקה", "Erleada": "ארלאדה",
    "Nexavar": "נקסבר", "Sorafenib": "סורפניב",
    "Sutent": "סוטנט", "Sunitinib": "סוניטיניב",
    "Votrient": "וטריאנט", "Pazopanib": "פזופניב",
    "Inlyta": "אינליטה", "Axitinib": "אקסיטיניב",
    "Cabometyx": "קבומטיקס", "Cabozantinib": "קבוזנטיניב",
    "Lenvima": "לנוימה", "Lenvatinib": "לנווטיניב",
    "Stivarga": "סטיורגה", "Regorafenib": "רגורפניב",
    "Revlimid": "רבלימיד", "Lenalidomide": "לנלידומיד",
    "Velcade": "וולקייד", "Bortezomib": "בורטזומיב",
    "Kyprolis": "קיפרוליס", "Carfilzomib": "קרפילזומיב",
    "Ninlaro": "נינלרו", "Ixazomib": "איקסזומיב",
    "Darzalex": "דרזלקס", "Daratumumab": "דרטומומב",
    "Pomalyst": "פומליסט", "Pomalidomide": "פומלידומיד",
    # אונקולוגיה — אימונותרפיה
    "Keytruda": "קייטרודה", "Pembrolizumab": "פמברוליזומב",
    "Opdivo": "אופדיבו", "Nivolumab": "ניבולומב",
    "Tecentriq": "טסנטריק", "Atezolizumab": "אטזוליזומב",
    "Imfinzi": "אימפינזי", "Durvalumab": "דורבלומב",
    "Bavencio": "בבנציו", "Avelumab": "אבלומב",
    "Yervoy": "ירבוי", "Ipilimumab": "איפילימומב",
    "Libtayo": "ליבטיו", "Cemiplimab": "סמיפלימב",
    # אונקולוגיה — הורמונלי
    "Tamoxifen": "טמוקסיפן", "Nolvadex": "נולבדקס",
    "Femara": "פמרה", "Letrozole": "לטרוזול",
    "Arimidex": "ארימידקס", "Anastrozole": "אנסטרוזול",
    "Aromasin": "ארומסין", "Exemestane": "אקסמסטן",
    "Faslodex": "פסלודקס", "Fulvestrant": "פולבסטרנט",
    "Lupron": "לופרון", "Leuprolide": "לויפרוליד",
    "Zoladex": "זולדקס", "Goserelin": "גוסרלין",
    "Decapeptyl": "דקפפטיל", "Triptorelin": "טריפטורלין",
    "Firmagon": "פירמגון", "Degarelix": "דגרליקס",
    "Casodex": "קסודקס", "Bicalutamide": "ביקלוטמיד",
    # ראומטולוגיה
    "Plaquenil": "פלקווניל", "Hydroxychloroquine": "הידרוקסיכלורוקין",
    "Sulfasalazine": "סולפסלזין", "Azulfidine": "אזולפידין",
    "Leflunomide": "לפלונומיד", "Arava": "ארבה",
    "Prednisone": "פרדניזון", "Prednisolone": "פרדניזולון",
    "Methylprednisolone": "מתילפרדניזולון", "Medrol": "מדרול",
    "Humira": "הומירה", "Adalimumab": "אדלימומב",
    "Enbrel": "אנברל", "Etanercept": "אטנרספט",
    "Remicade": "רמיקייד", "Infliximab": "אינפליקסימב",
    "Simponi": "סימפוני", "Golimumab": "גולימומב",
    "Cimzia": "סימזיה", "Certolizumab Pegol": "סרטוליזומב פגול",
    "Orencia": "ורנציה", "Abatacept": "אבטספט",
    "Actemra": "אקטמרה", "Tocilizumab": "טוציליזומב",
    "Kevzara": "קוזרה", "Sarilumab": "סרילומב",
    "Rinvoq": "רינבוק", "Upadacitinib": "אופדציטיניב",
    "Xeljanz": "זלג'אנס", "Tofacitinib": "טופציטיניב",
    "Olumiant": "אולומיאנט", "Baricitinib": "ברציטיניב",
    "Cosentyx": "קוסנטיקס", "Secukinumab": "סקוקינומב",
    "Taltz": "טלץ", "Ixekizumab": "איקסקיזומב",
    "Tremfya": "טרמפיה", "Guselkumab": "גוסלקומב",
    "Stelara": "סטלארה", "Ustekinumab": "אוסטקינומב",
    "Skyrizi": "סקיריזי", "Risankizumab": "ריסנקיזומב",
    "Rituximab": "ריטוקסימב", "MabThera": "מבתרה",
    "Benlysta": "בנליסטה", "Belimumab": "בלימומב",
    "Mycophenolate": "מיקופנולט", "CellCept": "סלסמט",
    "Cyclosporine": "ציקלוספורין", "Neoral": "נאורל",
    "Tacrolimus": "טקרולימוס", "Prograf": "פרוגרף",
    "Azathioprine": "אזתיאופרין", "Imuran": "אימוראן",
    "Colchicine": "קולכיצין", "Allopurinol": "אלופורינול",
    "Zyloric": "זילוריק", "Febuxostat": "פבוקסוסטט", "Adenuric": "אדנוריק",
    # ריאות
    "Ventolin": "ונטולין", "Salbutamol": "סלבוטמול",
    "Bricanyl": "בריקניל", "Terbutaline": "טרבוטלין",
    "Formoterol": "פורמוטרול", "Salmeterol": "סלמטרול",
    "Flixotide": "פליקסוטייד", "Fluticasone": "פלוטיקזון",
    "Pulmicort": "פולמיקורט", "Budesonide": "בודסוניד",
    "Qvar": "קבאר", "Beclomethasone": "בקלומטזון",
    "Symbicort": "סימביקורט", "Seretide": "סרטייד",
    "Relvar": "רלבר", "Trelegy": "טרלג'י",
    "Spiriva": "ספיריבה", "Tiotropium": "טיוטרופיום",
    "Atrovent": "אטרובנט", "Ipratropium": "איפרטרופיום",
    "Daliresp": "דלירסף", "Roflumilast": "רופלומילסט",
    "Ofev": "אופב", "Nintedanib": "נינטדניב",
    "Esbriet": "אסבריאט", "Pirfenidone": "פירפנידון",
    "Dupixent": "דופיקסנט", "Dupilumab": "דופילומב",
    "Nucala": "נוקלה", "Mepolizumab": "מפוליזומב",
    "Fasenra": "פסנרה", "Benralizumab": "בנרליזומב",
    "Xolair": "זולייר", "Omalizumab": "אומליזומב",
    "Montelukast": "מונטלוקסט", "Singulair": "סינגולייר",
    "Theophylline": "תיאופילין",
    # גסטרו
    "Losec": "לוסק", "Omeprazole": "אומפרזול", "Omepradex": "אומפרדקס",
    "Nexium": "נקסיום", "Esomeprazole": "אסומפרזול",
    "Controloc": "קונטרולוק", "Pantoprazole": "פנטופרזול",
    "Lansoprazole": "לנסופרזול", "Rabeprazole": "רבפרזול",
    "Zantac": "זנטק", "Ranitidine": "רניטידין",
    "Motilium": "מוטיליום", "Domperidone": "דומפרידון",
    "Primpiran": "פרימפרן", "Metoclopramide": "מטוקלופרמיד",
    "Imodium": "אימודיום", "Loperamide": "לופרמיד",
    "Dulcolax": "דולקולקס", "Bisacodyl": "ביסקודיל",
    "Lactulose": "לקטולוז", "Macrogol": "מקרוגול", "Forlax": "פורלקס",
    "Buscopan": "בוסקופן",
    "Mezavant": "מזוונט", "Pentasa": "פנטסה",
    "Asacol": "אסקול", "Mesalazine": "מזלזין",
    "Ursofalk": "אורסופלק", "Ursodiol": "אורסודיול",
    "Rifaximin": "ריפקסימין", "Xifaxan": "זיפקסן",
    "Ondansetron": "אונדנסטרון", "Zofran": "זופרן",
    "Aprepitant": "אפרפיטנט", "Emend": "אמנד",
    "Entyvio": "אנטיביו", "Vedolizumab": "ודוליזומב",
    # כליות
    "Aranesp": "אראנספ", "Darbepoetin Alfa": "דרבפואטין",
    "Mircera": "מירסרה", "Renagel": "ריניג'ל", "Sevelamer": "סוולמר",
    "Cinacalcet": "סינקלסט", "Mimpara": "מימפרה",
    "Kerendia": "קרנדיה", "Finerenone": "פינרנון",
    # המטולוגיה
    "Ferinject": "פרינג'קט", "Venofer": "ונופר",
    "Ferrum Hausmann": "פרום הויסמן",
    "Neupogen": "נויפוגן", "Filgrastim": "פילגרסטים",
    "Neulasta": "נויאלסטה", "Jakavi": "ג'קבי", "Ruxolitinib": "רוקסוליטיניב",
    # אנטיביוטיקה
    "Amoxicillin": "אמוקסיצילין", "Augmentin": "אוגמנטין",
    "Amoxicillin + Clavulanate": "אמוקסיצילין + קלבולנט",
    "Azithromycin": "אזיתרומיצין", "Zithromax": "זיתרומקס",
    "Klacid": "קלאסיד", "Clarithromycin": "קלריתרומיצין",
    "Cipro": "ציפרו", "Ciprobay": "ציפרובי", "Ciprofloxacin": "ציפרופלוקסצין",
    "Levofloxacin": "לבופלוקסצין", "Tavanic": "טוואניק",
    "Moxifloxacin": "מוקסיפלוקסצין", "Avelox": "אבלוקס",
    "Doxycycline": "דוקסיציקלין", "Vibramycin": "ויברמיצין",
    "Tetracycline": "טטרציקלין", "Minocycline": "מינוציקלין",
    "Trimethoprim-Sulfamethoxazole": "טרימתופרים-סולפה",
    "Bactrim": "בקטרים", "Septrin": "ספטרין",
    "Metronidazole": "מטרונידזול", "Flagyl": "פלגיל",
    "Clindamycin": "קלינדמיצין", "Dalacin C": "דלצין C",
    "Vancomycin": "ונקומיצין", "Linezolid": "לינזוליד", "Zyvox": "זיבוקס",
    "Rifampicin": "ריפמפיצין", "Isoniazid": "איזוניאזיד",
    "Ethambutol": "אתמבוטול", "Pyrazinamide": "פירזינמיד",
    "Ceftriaxone": "צפטריאקסון", "Cefuroxime": "צפורוקסים",
    "Zinnat": "זינאט", "Cephalexin": "צפלקסין", "Keflex": "קפלקס",
    # אנטי-פטרייתי / ויראלי
    "Fluconazole": "פלוקונזול", "Diflucan": "דיפלוקן",
    "Itraconazole": "איטרקונזול", "Voriconazole": "ווריקונזול",
    "Acyclovir": "אציקלוביר", "Zovirax": "זוביירקס",
    "Valacyclovir": "ולציקלוביר", "Valtrex": "ולטרקס",
    "Famciclovir": "פמציקלוביר",
    "Oseltamivir": "אוסלטמיביר", "Tamiflu": "טמיפלו",
    # HIV
    "Truvada": "טרובדה", "Biktarvy": "ביקטרבי",
    "Genvoya": "ג'נבויה", "Triumeq": "טריומק",
    "Dolutegravir": "דולוטגרביר", "Tivicay": "טיביקי",
    "Raltegravir": "רלטגרביר", "Isentress": "איסנטרס",
    # אלרגיה / עור
    "Clarityn": "קלריטין", "Loratadine": "לורטדין",
    "Zyrtec": "זירטק", "Cetirizine": "צטיריזין",
    "Aerius": "אריוס", "Desloratadine": "דסלורטדין",
    "Allegra": "אלגרה", "Fexofenadine": "פקסופנדין",
    "Hydrocortisone": "הידרוקורטיזון",
    "Betamethasone": "בטמתזון", "Clobetasol": "קלובטסול",
    "Isotretinoin": "איזוטרטינואין", "Roaccutane": "רואקוטן",
    # עיניים
    "Eylea": "אילאה", "Aflibercept": "אפליברספט",
    "Lucentis": "לוסנטיס", "Ranibizumab": "רניביזומב",
    "Timolol": "טימולול", "Xalatan": "זלטן", "Latanoprost": "לטנופרוסט",
    "Cosopt": "קוסופט", "Lumigan": "לומיגן",
    # אוסטאופורוזיס
    "Fosamax": "פוסאמקס", "Alendronate": "אלנדרונט",
    "Bonviva": "בונויבה", "Ibandronate": "איבנדרונט",
    "Actonel": "אקטונל", "Risedronate": "ריזדרונט",
    "Prolia": "פרוליה", "Denosumab": "דנוסומב",
    "Evenity": "אוונייטי", "Romosozumab": "רומוסוזומב",
    "Forteo": "פורטאו", "Teriparatide": "טריפרטייד",
    "Calcium D3": "סידן D3", "Vitamin D3": "ויטמין D3",
    # שתן / פרוסטטה
    "Omnic": "אומניק", "Tamsulosin": "טמסולוסין",
    "Alfuzosin": "אלפוזוסין", "Xatral": "זטרל",
    "Finasteride": "פינסטריד", "Proscar": "פרוסקר",
    "Avodart": "אבודרט", "Dutasteride": "דוטסטריד",
    "Detrusitol": "דטרוסיטול", "Vesicare": "וסיקר",
    "Toviaz": "טוביאז", "Myrbetriq": "מירבטריק",
    # מיגרנה
    "Imigran": "אימיגרן", "Sumatriptan": "סומטריפטן",
    "Zomig": "זומיג", "Maxalt": "מקסלט", "Relpax": "רלפקס",
    "Nurtec": "נורטק", "Aimovig": "אימוביג",
    "Ajovy": "אג'ובי", "Emgality": "אמגליטי",
    "Botox": "בוטוקס",
    # ויטמינים
    "Vitamin B12": "ויטמין B12", "Folic Acid": "חומצה פולית",
    "Vitamin C": "ויטמין C", "Vitamin K": "ויטמין K",
    "Magnesium": "מגנזיום", "Potassium Chloride": "אשלגן כלורי",
    "Slow-K": "סלואו-K", "Iron Supplement": "תוסף ברזל",
    "Zinc": "אבץ", "Omega-3": "אומגה 3", "Omacor": "אומקור",
    "Calcium Carbonate": "סידן", "Calcium D3": "סידן D3",
    # הורמונלי
    "Hydrocortisone": "הידרוקורטיזון",
    "Dexamethasone": "דקסמתזון", "Florinef": "פלורינף",
    "Somatropin": "סומטרופין", "Octreotide": "אוקטריאוטיד",
    "Sandostatin": "סנדוסטטין", "Androgel": "אנדרוג'ל",
    "Utrogestan": "אוטרוג'סטן",
    # שמירת הריון
    "Gestone": "ג'סטון", "Crinone": "קרינון",
    "Clomid": "קלומיד", "Puregon": "פורגון", "Gonal-F": "גונל F",
    "Pregnyl": "פרגניל", "Diphereline": "דיפרלין",
    # שונות
    "Sildenafil": "סילדנאפיל", "Viagra": "ויאגרה",
    "Cialis": "סיאליס", "Tadalafil": "טדלפיל",
    "Colchicine": "קולכיצין",
    # שרירים
    "Baclofen": "בקלופן", "Lioresal": "ליאורסל",
    "Zanaflex": "זנאפלקס", "Tizanidine": "טיזנידין",
    "Dantrium": "דנטריום", "Dantrolene": "דנטרולן",
    "Robaxin": "רובקסין", "Methocarbamol": "מתוקרבמול",
    "Cyclobenzaprine": "ציקלובנזפרין",
    # שלפוחית
    "Betamiga": "בטמיגה", "Mirabegron": "מירבגרון",
    "Myrbetriq": "מירבטריק", "Vesicare": "וסיקר",
    "Detrusitol": "דטרוסיטול", "Ditropan": "דיטרופן",
    # נוירולוגיה נדירות
    "Riluzole": "ריליוזול", "Rilutek": "ריליטק",
    "Baclofen": "בקלופן",
    # א.א.ג
    "Betahistine": "בטהיסטין", "Serc": "סרק",
    "Cinnarizine": "סינריזין", "Stugeron": "סטוגרון",
    "Scopolamine": "סקופולמין", "Scopoderm": "סקופודרם",
    "Promethazine": "פרומתזין", "Phenergan": "פנרגן",
    "Dimenhydrinate": "דימנהידרינט", "Dramamine": "דרממין",
    # קרדיולוגיה נוספות
    "Sacubitril": "סקוביטריל",
    "Labetalol": "לבטלול", "Trandate": "טרנדט",
    "Minoxidil oral": "מינוקסידיל פומי",
    "Minoxidil topical": "מינוקסידיל מקומי",
    "Rogaine": "רוגיין",
    # עור
    "Tretinoin": "טרטינואין", "Retin-A": "רטין A",
    "Adapalene": "אדפלן", "Differin": "דיפרין",
    "Apremilast": "אפרמילסט", "Otezla": "אוטזלה",
    "Calcipotriol": "קלציפוטריאול",
    # עיניים נוספות
    "Latanoprost": "לטנופרוסט", "Xalatan": "זלטן",
    "Travoprost": "טרבופרוסט", "Bimatoprost": "בימטופרוסט",
    "Brimonidine": "ברימונידין", "Alphagan": "אלפגן",
    "Lifitegrast": "ליפיטגרסט", "Xiidra": "זיידרה",
    "Faricimab": "פריצימב", "Vabysmo": "ובייסמו",
    # המטולוגיה
    "Tranexamic Acid": "חומצה טרנקסמית", "Cyklokapron": "ציקלוקפרון",
    "Eltrombopag": "אלטרומבופג", "Revolade": "רוולייד",
    "Romiplostim": "רומיפלוסטים", "Nplate": "אנפלייט",
    "Deferasirox": "דפרסירוקס", "Exjade": "אקסג'ייד",
    "Deferiprone": "דפריפרון", "Ferriprox": "פריפרוקס",
    "Desmopressin": "דסמופרסין", "Minirin": "מינירין",
    # הרדמה / כאב
    "Ketamine": "קטמין", "Naloxone": "נלוקסון",
    "Narcan": "נרקן", "Naltrexone": "נלטרקסון",
    "Suboxone": "סובוקסון", "Subutex": "סובוטקס",
    "Lidocaine": "לידוקאין", "Xylocaine": "זילוקאין",
    "Bupivacaine": "בופיבקאין", "Marcain": "מרקאין",
}

DRUGS = [
    # ═══════════════════════════════════════════════════
    # כאב / אנטי-דלקתי / חום
    # ═══════════════════════════════════════════════════
    ("Acamol", "Paracetamol", "טבליות"),
    ("Paracetamol", "Paracetamol", "טבליות"),
    ("Optalgin", "Dipyrone (Metamizole)", "טבליות"),
    ("Dipyrone", "Dipyrone", "טבליות"),
    ("Ibufen", "Ibuprofen", "טבליות"),
    ("Advil", "Ibuprofen", "טבליות"),
    ("Ibuprofen", "Ibuprofen", "טבליות"),
    ("Voltaren", "Diclofenac", "טבליות / ג'ל"),
    ("Diclofenac", "Diclofenac", "טבליות"),
    ("Arcoxia", "Etoricoxib", "טבליות"),
    ("Celebrex", "Celecoxib", "כמוסות"),
    ("Celecoxib", "Celecoxib", "כמוסות"),
    ("Naproxen", "Naproxen", "טבליות"),
    ("Proxen", "Naproxen", "טבליות"),
    ("Indocid", "Indomethacin", "כמוסות"),
    ("Tramadex", "Tramadol", "טבליות"),
    ("Tramadol", "Tramadol", "טבליות"),
    ("Ultram", "Tramadol", "טבליות"),
    ("Zaldiar", "Tramadol + Paracetamol", "טבליות"),
    ("Oxycontin", "Oxycodone", "טבליות"),
    ("Oxycodone", "Oxycodone", "טבליות"),
    ("Norspan", "Buprenorphine", "מדבקה"),
    ("Buprenorphine", "Buprenorphine", "מדבקה / תת-לשונית"),
    ("Fentanyl", "Fentanyl", "מדבקה"),
    ("Durogesic", "Fentanyl", "מדבקה"),
    ("Morphine", "Morphine Sulfate", "טבליות / זריקה"),
    ("Sevredol", "Morphine", "טבליות"),
    ("MST Continus", "Morphine Sulfate CR", "טבליות"),
    ("Lyrica", "Pregabalin", "כמוסות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Neurontin", "Gabapentin", "כמוסות"),
    ("Gabapentin", "Gabapentin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # לב וכלי דם — יתר לחץ דם
    # ═══════════════════════════════════════════════════
    ("Enalapril", "Enalapril", "טבליות"),
    ("Ramipril", "Ramipril", "טבליות"),
    ("Tritace", "Ramipril", "טבליות"),
    ("Lisinopril", "Lisinopril", "טבליות"),
    ("Zestril", "Lisinopril", "טבליות"),
    ("Perindopril", "Perindopril", "טבליות"),
    ("Coversyl", "Perindopril", "טבליות"),
    ("Captopril", "Captopril", "טבליות"),
    ("Losartan", "Losartan", "טבליות"),
    ("Cozaar", "Losartan", "טבליות"),
    ("Valsartan", "Valsartan", "טבליות"),
    ("Diovan", "Valsartan", "טבליות"),
    ("Irbesartan", "Irbesartan", "טבליות"),
    ("Candesartan", "Candesartan", "טבליות"),
    ("Olmesartan", "Olmesartan", "טבליות"),
    ("Concor", "Bisoprolol", "טבליות"),
    ("Bisoprolol", "Bisoprolol", "טבליות"),
    ("Betaloc", "Metoprolol", "טבליות"),
    ("Metoprolol", "Metoprolol", "טבליות"),
    ("Atenolol", "Atenolol", "טבליות"),
    ("Carvedilol", "Carvedilol", "טבליות"),
    ("Norvasc", "Amlodipine", "טבליות"),
    ("Amlopin", "Amlodipine", "טבליות"),
    ("Amlodipine", "Amlodipine", "טבליות"),
    ("Felodipine", "Felodipine", "טבליות"),
    ("Nifedipine", "Nifedipine", "טבליות"),
    ("Verapamil", "Verapamil", "טבליות"),
    ("Diltiazem", "Diltiazem", "טבליות"),
    ("Doxazosin", "Doxazosin", "טבליות"),
    ("Moxonidine", "Moxonidine", "טבליות"),
    ("Clonidine", "Clonidine", "טבליות"),
    ("Methyldopa", "Methyldopa", "טבליות"),
    ("Hydralazine", "Hydralazine", "טבליות"),
    ("Nitroglycerin", "Nitroglycerin", "תת-לשוני / מדבקה"),
    ("Isorind", "Isosorbide Dinitrate", "טבליות"),

    # ═══════════════════════════════════════════════════
    # לב — אי ספיקה / הפרעות קצב
    # ═══════════════════════════════════════════════════
    ("Digoxin", "Digoxin", "טבליות"),
    ("Lanoxin", "Digoxin", "טבליות"),
    ("Amiodarone", "Amiodarone", "טבליות"),
    ("Cordarone", "Amiodarone", "טבליות"),
    ("Entresto", "Sacubitril + Valsartan", "טבליות"),
    ("Coreg", "Carvedilol", "טבליות"),
    ("Inspra", "Eplerenone", "טבליות"),
    ("Veroshpiron", "Spironolactone", "טבליות"),
    ("Ivabradine", "Ivabradine", "טבליות"),
    ("Procoralan", "Ivabradine", "טבליות"),
    ("Sotalol", "Sotalol", "טבליות"),
    ("Flecainide", "Flecainide", "טבליות"),
    ("Propafenone", "Propafenone", "טבליות"),
    ("Tambocor", "Flecainide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # משתנים
    # ═══════════════════════════════════════════════════
    ("Lasix", "Furosemide", "טבליות"),
    ("Furosemide", "Furosemide", "טבליות"),
    ("Aldactone", "Spironolactone", "טבליות"),
    ("Spironolactone", "Spironolactone", "טבליות"),
    ("Moduretic", "Amiloride + Hydrochlorothiazide", "טבליות"),
    ("Hydrochlorothiazide", "Hydrochlorothiazide", "טבליות"),
    ("Indapamide", "Indapamide", "טבליות"),
    ("Torsemide", "Torsemide", "טבליות"),
    ("Bumetanide", "Bumetanide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוגדי קרישה / אנטי-טסיות
    # ═══════════════════════════════════════════════════
    ("Aspirin Cardio", "Aspirin", "טבליות"),
    ("Aspirin", "Aspirin", "טבליות"),
    ("Plavix", "Clopidogrel", "טבליות"),
    ("Clopidogrel", "Clopidogrel", "טבליות"),
    ("Brilique", "Ticagrelor", "טבליות"),
    ("Ticagrelor", "Ticagrelor", "טבליות"),
    ("Prasugrel", "Prasugrel", "טבליות"),
    ("Effient", "Prasugrel", "טבליות"),
    ("Coumadin", "Warfarin", "טבליות"),
    ("Warfarin", "Warfarin", "טבליות"),
    ("Xarelto", "Rivaroxaban", "טבליות"),
    ("Rivaroxaban", "Rivaroxaban", "טבליות"),
    ("Eliquis", "Apixaban", "טבליות"),
    ("Apixaban", "Apixaban", "טבליות"),
    ("Pradaxa", "Dabigatran", "כמוסות"),
    ("Dabigatran", "Dabigatran", "כמוסות"),
    ("Lixiana", "Edoxaban", "טבליות"),
    ("Heparin", "Heparin", "זריקה"),
    ("Clexane", "Enoxaparin", "זריקה"),
    ("Enoxaparin", "Enoxaparin", "זריקה"),
    ("Fragmin", "Dalteparin", "זריקה"),
    ("Innohep", "Tinzaparin", "זריקה"),
    ("Dipyridamole", "Dipyridamole", "טבליות"),
    ("Persantin", "Dipyridamole", "טבליות"),

    # ═══════════════════════════════════════════════════
    # כולסטרול / שומנים
    # ═══════════════════════════════════════════════════
    ("Lipitor", "Atorvastatin", "טבליות"),
    ("Atorvastatin", "Atorvastatin", "טבליות"),
    ("Crestor", "Rosuvastatin", "טבליות"),
    ("Rosuvastatin", "Rosuvastatin", "טבליות"),
    ("Zocor", "Simvastatin", "טבליות"),
    ("Simvastatin", "Simvastatin", "טבליות"),
    ("Pravastatin", "Pravastatin", "טבליות"),
    ("Fluvastatin", "Fluvastatin", "כמוסות"),
    ("Pitavastatin", "Pitavastatin", "טבליות"),
    ("Ezetimibe", "Ezetimibe", "טבליות"),
    ("Ezetrol", "Ezetimibe", "טבליות"),
    ("Inegy", "Ezetimibe + Simvastatin", "טבליות"),
    ("Repatha", "Evolocumab", "זריקה"),
    ("Praluent", "Alirocumab", "זריקה"),
    ("Fenofibrate", "Fenofibrate", "טבליות"),
    ("Lipanthyl", "Fenofibrate", "טבליות"),
    ("Gemfibrozil", "Gemfibrozil", "טבליות"),
    ("Omega-3", "Omega-3 Fatty Acids", "כמוסות"),
    ("Omacor", "Omega-3", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # סוכרת
    # ═══════════════════════════════════════════════════
    ("Glucophage", "Metformin", "טבליות"),
    ("Metformin", "Metformin", "טבליות"),
    ("Januvia", "Sitagliptin", "טבליות"),
    ("Sitagliptin", "Sitagliptin", "טבליות"),
    ("Trajenta", "Linagliptin", "טבליות"),
    ("Galvus", "Vildagliptin", "טבליות"),
    ("Onglyza", "Saxagliptin", "טבליות"),
    ("Jardiance", "Empagliflozin", "טבליות"),
    ("Empagliflozin", "Empagliflozin", "טבליות"),
    ("Forxiga", "Dapagliflozin", "טבליות"),
    ("Dapagliflozin", "Dapagliflozin", "טבליות"),
    ("Invokana", "Canagliflozin", "טבליות"),
    ("Ozempic", "Semaglutide", "זריקה"),
    ("Semaglutide", "Semaglutide", "זריקה / טבליות"),
    ("Rybelsus", "Semaglutide", "טבליות"),
    ("Victoza", "Liraglutide", "זריקה"),
    ("Liraglutide", "Liraglutide", "זריקה"),
    ("Trulicity", "Dulaglutide", "זריקה"),
    ("Byetta", "Exenatide", "זריקה"),
    ("Toujeo", "Insulin Glargine U300", "זריקה"),
    ("Lantus", "Insulin Glargine", "זריקה"),
    ("Basaglar", "Insulin Glargine", "זריקה"),
    ("Tresiba", "Insulin Degludec", "זריקה"),
    ("Levemir", "Insulin Detemir", "זריקה"),
    ("Novorapid", "Insulin Aspart", "זריקה"),
    ("Humalog", "Insulin Lispro", "זריקה"),
    ("Apidra", "Insulin Glulisine", "זריקה"),
    ("Humulin R", "Regular Insulin", "זריקה"),
    ("Humulin N", "NPH Insulin", "זריקה"),
    ("Mixtard", "Biphasic Insulin", "זריקה"),
    ("Amaryl", "Glimepiride", "טבליות"),
    ("Glimepiride", "Glimepiride", "טבליות"),
    ("Glipizide", "Glipizide", "טבליות"),
    ("Gliclazide", "Gliclazide", "טבליות"),
    ("Pioglitazone", "Pioglitazone", "טבליות"),
    ("Acarbose", "Acarbose", "טבליות"),
    ("Repaglinide", "Repaglinide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # בלוטת תריס
    # ═══════════════════════════════════════════════════
    ("Eltroxin", "Levothyroxine", "טבליות"),
    ("Euthyrox", "Levothyroxine", "טבליות"),
    ("Levothyroxine", "Levothyroxine", "טבליות"),
    ("Synthroid", "Levothyroxine", "טבליות"),
    ("Propylthiouracil", "Propylthiouracil", "טבליות"),
    ("Carbimazole", "Carbimazole", "טבליות"),
    ("Thyroblock", "Potassium Iodide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — אפילפסיה
    # ═══════════════════════════════════════════════════
    ("Tegretol", "Carbamazepine", "טבליות"),
    ("Carbamazepine", "Carbamazepine", "טבליות"),
    ("Depakine", "Valproic Acid", "טבליות"),
    ("Valproic Acid", "Valproic Acid", "טבליות"),
    ("Lamictal", "Lamotrigine", "טבליות"),
    ("Lamotrigine", "Lamotrigine", "טבליות"),
    ("Keppra", "Levetiracetam", "טבליות"),
    ("Levetiracetam", "Levetiracetam", "טבליות"),
    ("Topamax", "Topiramate", "כמוסות"),
    ("Topiramate", "Topiramate", "טבליות"),
    ("Phenobarbital", "Phenobarbital", "טבליות"),
    ("Luminal", "Phenobarbital", "טבליות"),
    ("Phenytoin", "Phenytoin", "כמוסות"),
    ("Dilantin", "Phenytoin", "כמוסות"),
    ("Oxcarbazepine", "Oxcarbazepine", "טבליות"),
    ("Trileptal", "Oxcarbazepine", "טבליות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Lyrica", "Pregabalin", "כמוסות"),
    ("Briviact", "Brivaracetam", "טבליות"),
    ("Vimpat", "Lacosamide", "טבליות"),
    ("Fycompa", "Perampanel", "טבליות"),
    ("Epidyolex", "Cannabidiol", "תמיסה"),
    ("Rivotril", "Clonazepam", "טבליות"),
    ("Clonazepam", "Clonazepam", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — פרקינסון
    # ═══════════════════════════════════════════════════
    ("Madopar", "Levodopa + Benserazide", "טבליות / כמוסות"),
    ("Sinemet", "Levodopa + Carbidopa", "טבליות"),
    ("Levodopa", "Levodopa", "טבליות"),
    ("Stalevo", "Levodopa + Carbidopa + Entacapone", "טבליות"),
    ("Requip", "Ropinirole", "טבליות"),
    ("Mirapex", "Pramipexole", "טבליות"),
    ("Neupro", "Rotigotine", "מדבקה"),
    ("Azilect", "Rasagiline", "טבליות"),
    ("Rasagiline", "Rasagiline", "טבליות"),
    ("Selegiline", "Selegiline", "טבליות"),
    ("Comtan", "Entacapone", "טבליות"),
    ("Tasmar", "Tolcapone", "טבליות"),
    ("Amantadine", "Amantadine", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — טרשת נפוצה (MS)
    # ═══════════════════════════════════════════════════
    ("Copaxone", "Glatiramer Acetate", "זריקה"),
    ("Avonex", "Interferon Beta-1a", "זריקה"),
    ("Rebif", "Interferon Beta-1a", "זריקה"),
    ("Betaferon", "Interferon Beta-1b", "זריקה"),
    ("Extavia", "Interferon Beta-1b", "זריקה"),
    ("Tecfidera", "Dimethyl Fumarate", "כמוסות"),
    ("Aubagio", "Teriflunomide", "טבליות"),
    ("Gilenya", "Fingolimod", "כמוסות"),
    ("Mayzent", "Siponimod", "טבליות"),
    ("Kesimpta", "Ofatumumab", "זריקה"),
    ("Ocrevus", "Ocrelizumab", "עירוי"),
    ("Tysabri", "Natalizumab", "עירוי"),
    ("Lemtrada", "Alemtuzumab", "עירוי"),
    ("Ponvory", "Ponesimod", "טבליות"),
    ("Zeposia", "Ozanimod", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — דמנציה / אלצהיימר
    # ═══════════════════════════════════════════════════
    ("Aricept", "Donepezil", "טבליות"),
    ("Donepezil", "Donepezil", "טבליות"),
    ("Exelon", "Rivastigmine", "טבליות / מדבקה"),
    ("Rivastigmine", "Rivastigmine", "כמוסות / מדבקה"),
    ("Reminyl", "Galantamine", "כמוסות"),
    ("Galantamine", "Galantamine", "כמוסות"),
    ("Ebixa", "Memantine", "טבליות / תמיסה"),
    ("Memantine", "Memantine", "טבליות"),

    # ═══════════════════════════════════════════════════
    # פסיכיאטריה — דיכאון / חרדה
    # ═══════════════════════════════════════════════════
    ("Cipralex", "Escitalopram", "טבליות"),
    ("Escitalopram", "Escitalopram", "טבליות"),
    ("Prozac", "Fluoxetine", "כמוסות"),
    ("Fluoxetine", "Fluoxetine", "כמוסות"),
    ("Zoloft", "Sertraline", "טבליות"),
    ("Sertraline", "Sertraline", "טבליות"),
    ("Effexor", "Venlafaxine", "כמוסות"),
    ("Venlafaxine", "Venlafaxine", "כמוסות"),
    ("Cymbalta", "Duloxetine", "כמוסות"),
    ("Duloxetine", "Duloxetine", "כמוסות"),
    ("Remeron", "Mirtazapine", "טבליות"),
    ("Mirtazapine", "Mirtazapine", "טבליות"),
    ("Paroxetine", "Paroxetine", "טבליות"),
    ("Citalopram", "Citalopram", "טבליות"),
    ("Fluvoxamine", "Fluvoxamine", "טבליות"),
    ("Anafranil", "Clomipramine", "טבליות"),
    ("Clomipramine", "Clomipramine", "טבליות"),
    ("Amitriptyline", "Amitriptyline", "טבליות"),
    ("Nortriptyline", "Nortriptyline", "טבליות"),
    ("Bupropion", "Bupropion", "טבליות"),
    ("Wellbutrin", "Bupropion", "טבליות"),
    ("Valdoxan", "Agomelatine", "טבליות"),
    ("Xanax", "Alprazolam", "טבליות"),
    ("Alprazolam", "Alprazolam", "טבליות"),
    ("Valium", "Diazepam", "טבליות"),
    ("Diazepam", "Diazepam", "טבליות"),
    ("Lorazepam", "Lorazepam", "טבליות"),
    ("Lorivan", "Lorazepam", "טבליות"),
    ("Buspirone", "Buspirone", "טבליות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Stilnox", "Zolpidem", "טבליות"),
    ("Zolpidem", "Zolpidem", "טבליות"),
    ("Imovane", "Zopiclone", "טבליות"),

    # ═══════════════════════════════════════════════════
    # פסיכיאטריה — אנטי-פסיכוטיים / מייצבי מצב רוח
    # ═══════════════════════════════════════════════════
    ("Risperdal", "Risperidone", "טבליות"),
    ("Risperidone", "Risperidone", "טבליות"),
    ("Zyprexa", "Olanzapine", "טבליות"),
    ("Olanzapine", "Olanzapine", "טבליות"),
    ("Seroquel", "Quetiapine", "טבליות"),
    ("Quetiapine", "Quetiapine", "טבליות"),
    ("Abilify", "Aripiprazole", "טבליות"),
    ("Aripiprazole", "Aripiprazole", "טבליות"),
    ("Clozaril", "Clozapine", "טבליות"),
    ("Clozapine", "Clozapine", "טבליות"),
    ("Haldol", "Haloperidol", "טבליות / זריקה"),
    ("Haloperidol", "Haloperidol", "טבליות"),
    ("Amisulpride", "Amisulpride", "טבליות"),
    ("Lithium", "Lithium Carbonate", "טבליות"),
    ("Camcolit", "Lithium Carbonate", "טבליות"),
    ("Depakote", "Valproate Semisodium", "טבליות"),
    ("Lamictal", "Lamotrigine", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ADHD
    # ═══════════════════════════════════════════════════
    ("Ritalin", "Methylphenidate", "טבליות"),
    ("Methylphenidate", "Methylphenidate", "טבליות"),
    ("Concerta", "Methylphenidate ER", "טבליות"),
    ("Medikinet", "Methylphenidate", "כמוסות"),
    ("Adderall", "Amphetamine Salts", "טבליות"),
    ("Strattera", "Atomoxetine", "כמוסות"),
    ("Atomoxetine", "Atomoxetine", "כמוסות"),
    ("Intuniv", "Guanfacine ER", "טבליות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — כימותרפיה קלאסית
    # ═══════════════════════════════════════════════════
    ("Cyclophosphamide", "Cyclophosphamide", "טבליות / זריקה"),
    ("Methotrexate", "Methotrexate", "טבליות / זריקה"),
    ("Fluorouracil", "5-Fluorouracil (5-FU)", "זריקה"),
    ("Capecitabine", "Capecitabine", "טבליות"),
    ("Xeloda", "Capecitabine", "טבליות"),
    ("Doxorubicin", "Doxorubicin", "זריקה"),
    ("Adriamycin", "Doxorubicin", "זריקה"),
    ("Epirubicin", "Epirubicin", "זריקה"),
    ("Paclitaxel", "Paclitaxel", "זריקה"),
    ("Taxol", "Paclitaxel", "זריקה"),
    ("Docetaxel", "Docetaxel", "זריקה"),
    ("Taxotere", "Docetaxel", "זריקה"),
    ("Carboplatin", "Carboplatin", "זריקה"),
    ("Cisplatin", "Cisplatin", "זריקה"),
    ("Oxaliplatin", "Oxaliplatin", "זריקה"),
    ("Eloxatin", "Oxaliplatin", "זריקה"),
    ("Gemcitabine", "Gemcitabine", "זריקה"),
    ("Gemzar", "Gemcitabine", "זריקה"),
    ("Vinorelbine", "Vinorelbine", "טבליות / זריקה"),
    ("Irinotecan", "Irinotecan", "זריקה"),
    ("Etoposide", "Etoposide", "כמוסות / זריקה"),
    ("Pemetrexed", "Pemetrexed", "זריקה"),
    ("Alimta", "Pemetrexed", "זריקה"),
    ("Melphalan", "Melphalan", "טבליות"),
    ("Chlorambucil", "Chlorambucil", "טבליות"),
    ("Bleomycin", "Bleomycin", "זריקה"),
    ("Vincristine", "Vincristine", "זריקה"),
    ("Cytarabine", "Cytarabine (Ara-C)", "זריקה"),
    ("Dacarbazine", "Dacarbazine", "זריקה"),
    ("Temozolomide", "Temozolomide", "כמוסות"),
    ("Temodal", "Temozolomide", "כמוסות"),
    ("Hydroxymethylglutaryl", "Hydroxyurea", "כמוסות"),
    ("Hydroxyurea", "Hydroxyurea", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — טיפול ממוקד (Targeted Therapy)
    # ═══════════════════════════════════════════════════
    ("Herceptin", "Trastuzumab", "עירוי"),
    ("Trastuzumab", "Trastuzumab", "עירוי"),
    ("Kadcyla", "Trastuzumab emtansine (T-DM1)", "עירוי"),
    ("Enhertu", "Trastuzumab deruxtecan", "עירוי"),
    ("Perjeta", "Pertuzumab", "עירוי"),
    ("Avastin", "Bevacizumab", "עירוי"),
    ("Bevacizumab", "Bevacizumab", "עירוי"),
    ("Erbitux", "Cetuximab", "עירוי"),
    ("Vectibix", "Panitumumab", "עירוי"),
    ("Gleevec", "Imatinib", "טבליות"),
    ("Imatinib", "Imatinib", "טבליות"),
    ("Tasigna", "Nilotinib", "כמוסות"),
    ("Sprycel", "Dasatinib", "טבליות"),
    ("Bosulif", "Bosutinib", "טבליות"),
    ("Iclusig", "Ponatinib", "טבליות"),
    ("Tarceva", "Erlotinib", "טבליות"),
    ("Iressa", "Gefitinib", "טבליות"),
    ("Gilotrif", "Afatinib", "טבליות"),
    ("Tagrisso", "Osimertinib", "טבליות"),
    ("Xalkori", "Crizotinib", "כמוסות"),
    ("Alecensa", "Alectinib", "כמוסות"),
    ("Lorbrena", "Lorlatinib", "טבליות"),
    ("Zelboraf", "Vemurafenib", "טבליות"),
    ("Tafinlar", "Dabrafenib", "כמוסות"),
    ("Mekinist", "Trametinib", "טבליות"),
    ("Cotellic", "Cobimetinib", "טבליות"),
    ("Ibrance", "Palbociclib", "כמוסות"),
    ("Kisqali", "Ribociclib", "טבליות"),
    ("Verzenio", "Abemaciclib", "טבליות"),
    ("Lynparza", "Olaparib", "טבליות"),
    ("Zejula", "Niraparib", "כמוסות"),
    ("Rubraca", "Rucaparib", "טבליות"),
    ("Imbruvica", "Ibrutinib", "כמוסות"),
    ("Calquence", "Acalabrutinib", "כמוסות"),
    ("Brukinsa", "Zanubrutinib", "כמוסות"),
    ("Venclexta", "Venetoclax", "טבליות"),
    ("Zytiga", "Abiraterone", "טבליות"),
    ("Xtandi", "Enzalutamide", "כמוסות"),
    ("Nubeqa", "Darolutamide", "טבליות"),
    ("Erleada", "Apalutamide", "טבליות"),
    ("Nexavar", "Sorafenib", "טבליות"),
    ("Sutent", "Sunitinib", "כמוסות"),
    ("Votrient", "Pazopanib", "טבליות"),
    ("Inlyta", "Axitinib", "טבליות"),
    ("Cabometyx", "Cabozantinib", "טבליות"),
    ("Lenvima", "Lenvatinib", "כמוסות"),
    ("Stivarga", "Regorafenib", "טבליות"),
    ("Revlimid", "Lenalidomide", "כמוסות"),
    ("Velcade", "Bortezomib", "זריקה"),
    ("Kyprolis", "Carfilzomib", "עירוי"),
    ("Ninlaro", "Ixazomib", "כמוסות"),
    ("Darzalex", "Daratumumab", "עירוי"),
    ("Pomalyst", "Pomalidomide", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — אימונותרפיה
    # ═══════════════════════════════════════════════════
    ("Keytruda", "Pembrolizumab", "עירוי"),
    ("Pembrolizumab", "Pembrolizumab", "עירוי"),
    ("Opdivo", "Nivolumab", "עירוי"),
    ("Nivolumab", "Nivolumab", "עירוי"),
    ("Tecentriq", "Atezolizumab", "עירוי"),
    ("Imfinzi", "Durvalumab", "עירוי"),
    ("Bavencio", "Avelumab", "עירוי"),
    ("Yervoy", "Ipilimumab", "עירוי"),
    ("Ipilimumab", "Ipilimumab", "עירוי"),
    ("Libtayo", "Cemiplimab", "עירוי"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — הורמונלי (שד / ערמונית)
    # ═══════════════════════════════════════════════════
    ("Tamoxifen", "Tamoxifen", "טבליות"),
    ("Nolvadex", "Tamoxifen", "טבליות"),
    ("Femara", "Letrozole", "טבליות"),
    ("Letrozole", "Letrozole", "טבליות"),
    ("Arimidex", "Anastrozole", "טבליות"),
    ("Anastrozole", "Anastrozole", "טבליות"),
    ("Aromasin", "Exemestane", "טבליות"),
    ("Faslodex", "Fulvestrant", "זריקה"),
    ("Lupron", "Leuprolide", "זריקה"),
    ("Zoladex", "Goserelin", "זריקה"),
    ("Decapeptyl", "Triptorelin", "זריקה"),
    ("Firmagon", "Degarelix", "זריקה"),
    ("Casodex", "Bicalutamide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ראומטולוגיה / מחלות אוטואימוניות
    # ═══════════════════════════════════════════════════
    ("Methotrexate", "Methotrexate", "טבליות / זריקה"),
    ("Plaquenil", "Hydroxychloroquine", "טבליות"),
    ("Hydroxychloroquine", "Hydroxychloroquine", "טבליות"),
    ("Sulfasalazine", "Sulfasalazine", "טבליות"),
    ("Azulfidine", "Sulfasalazine", "טבליות"),
    ("Leflunomide", "Leflunomide", "טבליות"),
    ("Arava", "Leflunomide", "טבליות"),
    ("Prednisone", "Prednisone", "טבליות"),
    ("Prednisolone", "Prednisolone", "טבליות"),
    ("Methylprednisolone", "Methylprednisolone", "טבליות / זריקה"),
    ("Medrol", "Methylprednisolone", "טבליות"),
    ("Humira", "Adalimumab", "זריקה"),
    ("Adalimumab", "Adalimumab", "זריקה"),
    ("Enbrel", "Etanercept", "זריקה"),
    ("Etanercept", "Etanercept", "זריקה"),
    ("Remicade", "Infliximab", "עירוי"),
    ("Infliximab", "Infliximab", "עירוי"),
    ("Simponi", "Golimumab", "זריקה"),
    ("Cimzia", "Certolizumab Pegol", "זריקה"),
    ("Orencia", "Abatacept", "זריקה / עירוי"),
    ("Actemra", "Tocilizumab", "עירוי / זריקה"),
    ("Kevzara", "Sarilumab", "זריקה"),
    ("Rinvoq", "Upadacitinib", "טבליות"),
    ("Xeljanz", "Tofacitinib", "טבליות"),
    ("Olumiant", "Baricitinib", "טבליות"),
    ("Cosentyx", "Secukinumab", "זריקה"),
    ("Taltz", "Ixekizumab", "זריקה"),
    ("Tremfya", "Guselkumab", "זריקה"),
    ("Stelara", "Ustekinumab", "זריקה / עירוי"),
    ("Skyrizi", "Risankizumab", "זריקה"),
    ("Rituximab", "Rituximab", "עירוי"),
    ("MabThera", "Rituximab", "עירוי"),
    ("Benlysta", "Belimumab", "עירוי / זריקה"),
    ("Mycophenolate", "Mycophenolate Mofetil", "כמוסות"),
    ("CellCept", "Mycophenolate Mofetil", "כמוסות"),
    ("Cyclosporine", "Cyclosporine", "כמוסות"),
    ("Neoral", "Cyclosporine", "כמוסות"),
    ("Tacrolimus", "Tacrolimus", "כמוסות"),
    ("Prograf", "Tacrolimus", "כמוסות"),
    ("Azathioprine", "Azathioprine", "טבליות"),
    ("Imuran", "Azathioprine", "טבליות"),
    ("Colchicine", "Colchicine", "טבליות"),
    ("Allopurinol", "Allopurinol", "טבליות"),
    ("Zyloric", "Allopurinol", "טבליות"),
    ("Febuxostat", "Febuxostat", "טבליות"),
    ("Adenuric", "Febuxostat", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ריאות / נשימה
    # ═══════════════════════════════════════════════════
    ("Ventolin", "Salbutamol", "אינהלר"),
    ("Salbutamol", "Salbutamol", "אינהלר"),
    ("Bricanyl", "Terbutaline", "אינהלר"),
    ("Formoterol", "Formoterol", "אינהלר"),
    ("Salmeterol", "Salmeterol", "אינהלר"),
    ("Flixotide", "Fluticasone", "אינהלר"),
    ("Pulmicort", "Budesonide", "אינהלר"),
    ("Qvar", "Beclomethasone", "אינהלר"),
    ("Alvesco", "Ciclesonide", "אינהלר"),
    ("Symbicort", "Budesonide + Formoterol", "אינהלר"),
    ("Seretide", "Salmeterol + Fluticasone", "אינהלר"),
    ("Relvar", "Vilanterol + Fluticasone", "אינהלר"),
    ("Trelegy", "FF + Vilanterol + UMEC", "אינהלר"),
    ("Spiriva", "Tiotropium", "אינהלר"),
    ("Tiotropium", "Tiotropium", "אינהלר"),
    ("Incruse", "Umeclidinium", "אינהלר"),
    ("Bretaris", "Aclidinium", "אינהלר"),
    ("Atrovent", "Ipratropium", "אינהלר"),
    ("Ipratropium", "Ipratropium", "אינהלר"),
    ("Daliresp", "Roflumilast", "טבליות"),
    ("Zithromax", "Azithromycin", "טבליות"),
    ("Ofev", "Nintedanib", "כמוסות"),
    ("Esbriet", "Pirfenidone", "כמוסות"),
    ("Dupixent", "Dupilumab", "זריקה"),
    ("Nucala", "Mepolizumab", "זריקה"),
    ("Fasenra", "Benralizumab", "זריקה"),
    ("Cinqair", "Reslizumab", "עירוי"),
    ("Xolair", "Omalizumab", "זריקה"),
    ("Montelukast", "Montelukast", "טבליות"),
    ("Singulair", "Montelukast", "טבליות"),
    ("Theophylline", "Theophylline", "טבליות"),

    # ═══════════════════════════════════════════════════
    # גסטרואנטרולוגיה
    # ═══════════════════════════════════════════════════
    ("Losec", "Omeprazole", "כמוסות"),
    ("Omepradex", "Omeprazole", "כמוסות"),
    ("Omeprazole", "Omeprazole", "כמוסות"),
    ("Nexium", "Esomeprazole", "טבליות"),
    ("Esomeprazole", "Esomeprazole", "טבליות"),
    ("Controloc", "Pantoprazole", "טבליות"),
    ("Pantoprazole", "Pantoprazole", "טבליות"),
    ("Lansoprazole", "Lansoprazole", "כמוסות"),
    ("Rabeprazole", "Rabeprazole", "טבליות"),
    ("Zantac", "Ranitidine", "טבליות"),
    ("Motilium", "Domperidone", "טבליות"),
    ("Primpiran", "Metoclopramide", "טבליות"),
    ("Metoclopramide", "Metoclopramide", "טבליות"),
    ("Imodium", "Loperamide", "טבליות"),
    ("Loperamide", "Loperamide", "טבליות"),
    ("Dulcolax", "Bisacodyl", "טבליות / סופוזיטוריה"),
    ("Lactulose", "Lactulose", "תמיסה"),
    ("Macrogol", "Polyethylene Glycol", "אבקה"),
    ("Forlax", "Macrogol", "אבקה"),
    ("Buscopan", "Hyoscine Butylbromide", "טבליות"),
    ("Mezavant", "Mesalazine", "טבליות"),
    ("Pentasa", "Mesalazine", "טבליות / כמוסות"),
    ("Asacol", "Mesalazine", "טבליות"),
    ("Mesalazine", "Mesalazine", "טבליות"),
    ("Budenofalk", "Budesonide", "כמוסות"),
    ("Remicade", "Infliximab", "עירוי"),
    ("Entyvio", "Vedolizumab", "עירוי"),
    ("Stelara", "Ustekinumab", "עירוי"),
    ("Ursofalk", "Ursodeoxycholic Acid", "כמוסות"),
    ("Ursodiol", "Ursodeoxycholic Acid", "כמוסות"),
    ("Rifaximin", "Rifaximin", "טבליות"),
    ("Xifaxan", "Rifaximin", "טבליות"),
    ("Ondansetron", "Ondansetron", "טבליות"),
    ("Zofran", "Ondansetron", "טבליות"),
    ("Aprepitant", "Aprepitant", "כמוסות"),
    ("Emend", "Aprepitant", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # כליות / נפרולוגיה
    # ═══════════════════════════════════════════════════
    ("Erythropoietin", "Erythropoietin (EPO)", "זריקה"),
    ("Aranesp", "Darbepoetin Alfa", "זריקה"),
    ("Mircera", "Methoxy PEG-Epoetin Beta", "זריקה"),
    ("Renagel", "Sevelamer", "טבליות"),
    ("Sevelamer", "Sevelamer", "טבליות"),
    ("Calcium Carbonate", "Calcium Carbonate", "טבליות"),
    ("Paricalcitol", "Paricalcitol", "כמוסות / זריקה"),
    ("Cinacalcet", "Cinacalcet", "טבליות"),
    ("Mimpara", "Cinacalcet", "טבליות"),
    ("Patiromer", "Patiromer", "אבקה"),
    ("Veltassa", "Patiromer", "אבקה"),
    ("Kerendia", "Finerenone", "טבליות"),
    ("Sodium Bicarbonate", "Sodium Bicarbonate", "טבליות"),

    # ═══════════════════════════════════════════════════
    # המטולוגיה
    # ═══════════════════════════════════════════════════
    ("Iron Supplement", "Iron (Ferrous Sulfate)", "טבליות"),
    ("Ferrum Hausmann", "Iron Polymaltose", "טבליות / זריקה"),
    ("Ferinject", "Ferric Carboxymaltose", "עירוי"),
    ("Venofer", "Iron Sucrose", "עירוי"),
    ("Vitamin B12", "Cyanocobalamin", "טבליות / זריקה"),
    ("Folic Acid", "Folic Acid", "טבליות"),
    ("Revlimid", "Lenalidomide", "כמוסות"),
    ("Thalidomide", "Thalidomide", "כמוסות"),
    ("Jakavi", "Ruxolitinib", "טבליות"),
    ("Calquence", "Acalabrutinib", "כמוסות"),
    ("Imbruvica", "Ibrutinib", "כמוסות"),
    ("G-CSF", "Filgrastim", "זריקה"),
    ("Neupogen", "Filgrastim", "זריקה"),
    ("Neulasta", "Pegfilgrastim", "זריקה"),

    # ═══════════════════════════════════════════════════
    # אנטיביוטיקה
    # ═══════════════════════════════════════════════════
    ("Amoxicillin", "Amoxicillin", "כמוסות"),
    ("Augmentin", "Amoxicillin + Clavulanate", "טבליות"),
    ("Amoxicillin + Clavulanate", "Amoxicillin + Clavulanate", "טבליות"),
    ("Azithromycin", "Azithromycin", "טבליות"),
    ("Zithromax", "Azithromycin", "טבליות"),
    ("Klacid", "Clarithromycin", "טבליות"),
    ("Clarithromycin", "Clarithromycin", "טבליות"),
    ("Cipro", "Ciprofloxacin", "טבליות"),
    ("Ciprobay", "Ciprofloxacin", "טבליות"),
    ("Ciprofloxacin", "Ciprofloxacin", "טבליות"),
    ("Levofloxacin", "Levofloxacin", "טבליות"),
    ("Tavanic", "Levofloxacin", "טבליות"),
    ("Moxifloxacin", "Moxifloxacin", "טבליות"),
    ("Avelox", "Moxifloxacin", "טבליות"),
    ("Doxycycline", "Doxycycline", "כמוסות"),
    ("Vibramycin", "Doxycycline", "כמוסות"),
    ("Tetracycline", "Tetracycline", "כמוסות"),
    ("Minocycline", "Minocycline", "כמוסות"),
    ("Trimethoprim-Sulfamethoxazole", "TMP-SMX", "טבליות"),
    ("Bactrim", "TMP-SMX", "טבליות"),
    ("Septrin", "TMP-SMX", "טבליות"),
    ("Metronidazole", "Metronidazole", "טבליות"),
    ("Flagyl", "Metronidazole", "טבליות"),
    ("Clindamycin", "Clindamycin", "כמוסות / זריקה"),
    ("Dalacin C", "Clindamycin", "כמוסות"),
    ("Vancomycin", "Vancomycin", "זריקה"),
    ("Linezolid", "Linezolid", "טבליות / עירוי"),
    ("Zyvox", "Linezolid", "טבליות"),
    ("Rifampicin", "Rifampicin", "כמוסות"),
    ("Isoniazid", "Isoniazid", "טבליות"),
    ("Ethambutol", "Ethambutol", "טבליות"),
    ("Pyrazinamide", "Pyrazinamide", "טבליות"),
    ("Ceftriaxone", "Ceftriaxone", "זריקה"),
    ("Cefuroxime", "Cefuroxime", "טבליות / זריקה"),
    ("Zinnat", "Cefuroxime Axetil", "טבליות"),
    ("Cephalexin", "Cephalexin", "כמוסות"),
    ("Keflex", "Cephalexin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אנטי-פטרייתי / אנטי-ויראלי
    # ═══════════════════════════════════════════════════
    ("Fluconazole", "Fluconazole", "כמוסות"),
    ("Diflucan", "Fluconazole", "כמוסות"),
    ("Itraconazole", "Itraconazole", "כמוסות"),
    ("Voriconazole", "Voriconazole", "טבליות"),
    ("Acyclovir", "Acyclovir", "טבליות"),
    ("Zovirax", "Acyclovir", "טבליות / משחה"),
    ("Valacyclovir", "Valacyclovir", "טבליות"),
    ("Valtrex", "Valacyclovir", "טבליות"),
    ("Famciclovir", "Famciclovir", "טבליות"),
    ("Oseltamivir", "Oseltamivir", "כמוסות"),
    ("Tamiflu", "Oseltamivir", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # HIV / AIDS
    # ═══════════════════════════════════════════════════
    ("Truvada", "Tenofovir + Emtricitabine", "טבליות"),
    ("Biktarvy", "Bictegravir + FTC + TAF", "טבליות"),
    ("Genvoya", "Elvitegravir combo", "טבליות"),
    ("Triumeq", "DTG + ABC + 3TC", "טבליות"),
    ("Dolutegravir", "Dolutegravir", "טבליות"),
    ("Tivicay", "Dolutegravir", "טבליות"),
    ("Atripla", "EFV + FTC + TDF", "טבליות"),
    ("Raltegravir", "Raltegravir", "טבליות"),
    ("Isentress", "Raltegravir", "טבליות"),

    # ═══════════════════════════════════════════════════
    # אלרגיה / עור
    # ═══════════════════════════════════════════════════
    ("Clarityn", "Loratadine", "טבליות"),
    ("Loratadine", "Loratadine", "טבליות"),
    ("Zyrtec", "Cetirizine", "טבליות"),
    ("Cetirizine", "Cetirizine", "טבליות"),
    ("Aerius", "Desloratadine", "טבליות"),
    ("Desloratadine", "Desloratadine", "טבליות"),
    ("Allegra", "Fexofenadine", "טבליות"),
    ("Fexofenadine", "Fexofenadine", "טבליות"),
    ("Hydrocortisone", "Hydrocortisone", "משחה / קרם"),
    ("Betamethasone", "Betamethasone", "משחה"),
    ("Clobetasol", "Clobetasol", "משחה"),
    ("Dupixent", "Dupilumab", "זריקה"),
    ("Skyrizi", "Risankizumab", "זריקה"),
    ("Tremfya", "Guselkumab", "זריקה"),
    ("Cosentyx", "Secukinumab", "זריקה"),
    ("Taltz", "Ixekizumab", "זריקה"),
    ("Humira", "Adalimumab", "זריקה"),
    ("Isotretinoin", "Isotretinoin", "כמוסות"),
    ("Roaccutane", "Isotretinoin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # עיניים
    # ═══════════════════════════════════════════════════
    ("Eylea", "Aflibercept", "זריקה תוך-עינית"),
    ("Lucentis", "Ranibizumab", "זריקה תוך-עינית"),
    ("Beovu", "Brolucizumab", "זריקה תוך-עינית"),
    ("Timolol", "Timolol", "טיפות עיניים"),
    ("Xalatan", "Latanoprost", "טיפות עיניים"),
    ("Cosopt", "Dorzolamide + Timolol", "טיפות עיניים"),
    ("Trusopt", "Dorzolamide", "טיפות עיניים"),
    ("Lumigan", "Bimatoprost", "טיפות עיניים"),

    # ═══════════════════════════════════════════════════
    # אוסטאופורוזיס
    # ═══════════════════════════════════════════════════
    ("Fosamax", "Alendronate", "טבליות"),
    ("Alendronate", "Alendronate", "טבליות"),
    ("Bonviva", "Ibandronate", "טבליות / זריקה"),
    ("Actonel", "Risedronate", "טבליות"),
    ("Prolia", "Denosumab", "זריקה"),
    ("Evenity", "Romosozumab", "זריקה"),
    ("Forteo", "Teriparatide", "זריקה"),
    ("Calcium D3", "Calcium + Vitamin D3", "טבליות"),
    ("Vitamin D3", "Cholecalciferol", "טיפות / טבליות"),

    # ═══════════════════════════════════════════════════
    # אנדוקרינולוגיה — שונות
    # ═══════════════════════════════════════════════════
    ("Hydrocortisone", "Hydrocortisone", "טבליות / זריקה"),
    ("Dexamethasone", "Dexamethasone", "טבליות / זריקה"),
    ("Florinef", "Fludrocortisone", "טבליות"),
    ("Somatropin", "Somatropin (GH)", "זריקה"),
    ("Octreotide", "Octreotide", "זריקה"),
    ("Sandostatin", "Octreotide", "זריקה"),
    ("Testosterone", "Testosterone", "ג'ל / זריקה"),
    ("Androgel", "Testosterone", "ג'ל"),
    ("Estradiol", "Estradiol", "טבליות / מדבקה"),
    ("Progesterone", "Progesterone", "כמוסות / ג'ל"),
    ("Utrogestan", "Progesterone", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # שתן / פרוסטטה
    # ═══════════════════════════════════════════════════
    ("Omnic", "Tamsulosin", "כמוסות"),
    ("Tamsulosin", "Tamsulosin", "כמוסות"),
    ("Alfuzosin", "Alfuzosin", "טבליות"),
    ("Xatral", "Alfuzosin", "טבליות"),
    ("Finasteride", "Finasteride", "טבליות"),
    ("Proscar", "Finasteride 5mg", "טבליות"),
    ("Avodart", "Dutasteride", "כמוסות"),
    ("Dutasteride", "Dutasteride", "כמוסות"),
    ("Detrusitol", "Tolterodine", "כמוסות"),
    ("Vesicare", "Solifenacin", "טבליות"),
    ("Toviaz", "Fesoterodine", "טבליות"),
    ("Myrbetriq", "Mirabegron", "טבליות"),

    # ═══════════════════════════════════════════════════
    # מיגרנה
    # ═══════════════════════════════════════════════════
    ("Imigran", "Sumatriptan", "טבליות"),
    ("Sumatriptan", "Sumatriptan", "טבליות"),
    ("Zomig", "Zolmitriptan", "טבליות"),
    ("Maxalt", "Rizatriptan", "טבליות"),
    ("Relpax", "Eletriptan", "טבליות"),
    ("Nurtec", "Rimegepant", "טבליות"),
    ("Ubrelvy", "Ubrogepant", "טבליות"),
    ("Aimovig", "Erenumab", "זריקה"),
    ("Ajovy", "Fremanezumab", "זריקה"),
    ("Emgality", "Galcanezumab", "זריקה"),
    ("Vyepti", "Eptinezumab", "עירוי"),
    ("Topamax", "Topiramate", "טבליות"),
    ("Propranolol", "Propranolol", "טבליות"),
    ("Amitriptyline", "Amitriptyline", "טבליות"),
    ("Botox", "Botulinum Toxin A", "זריקה"),

    # ═══════════════════════════════════════════════════
    # ויטמינים / תוספים
    # ═══════════════════════════════════════════════════
    ("Vitamin B12", "Cyanocobalamin", "טבליות / זריקה"),
    ("Folic Acid", "Folic Acid", "טבליות"),
    ("Vitamin D3", "Cholecalciferol", "טיפות / טבליות"),
    ("Vitamin C", "Ascorbic Acid", "טבליות"),
    ("Vitamin K", "Phytomenadione", "טבליות"),
    ("Magnesium", "Magnesium", "טבליות"),
    ("Potassium Chloride", "Potassium Chloride", "טבליות"),
    ("Slow-K", "Potassium Chloride", "טבליות"),
    ("Iron Supplement", "Ferrous Sulfate", "טבליות"),
    ("Zinc", "Zinc", "טבליות"),

    # ═══════════════════════════════════════════════════
    # שמירת הריון /妇科
    # ═══════════════════════════════════════════════════
    ("Gestone", "Progesterone", "זריקה"),
    ("Crinone", "Progesterone", "ג'ל"),
    ("Clomid", "Clomiphene", "טבליות"),
    ("Puregon", "Follitropin Beta", "זריקה"),
    ("Gonal-F", "Follitropin Alfa", "זריקה"),
    ("Pregnyl", "hCG", "זריקה"),
    ("Diphereline", "Triptorelin", "זריקה"),
    ("Lupron", "Leuprolide", "זריקה"),

    # ═══════════════════════════════════════════════════
    # שרירים ועמוד שדרה — Muscle Relaxants / Spasticity
    # ═══════════════════════════════════════════════════
    ("Baclofen", "Baclofen", "טבליות"),
    ("Lioresal", "Baclofen", "טבליות"),
    ("Zanaflex", "Tizanidine", "טבליות"),
    ("Tizanidine", "Tizanidine", "טבליות"),
    ("Dantrium", "Dantrolene", "כמוסות"),
    ("Dantrolene", "Dantrolene", "כמוסות"),
    ("Robaxin", "Methocarbamol", "טבליות"),
    ("Methocarbamol", "Methocarbamol", "טבליות"),
    ("Orphenadrine", "Orphenadrine", "טבליות"),
    ("Norflex", "Orphenadrine", "טבליות"),
    ("Cyclobenzaprine", "Cyclobenzaprine", "טבליות"),
    ("Flexeril", "Cyclobenzaprine", "טבליות"),
    ("Carisoprodol", "Carisoprodol", "טבליות"),
    ("Soma", "Carisoprodol", "טבליות"),
    ("Botox", "Botulinum Toxin A", "זריקה"),
    ("Dysport", "Botulinum Toxin A", "זריקה"),
    ("Xeomin", "Botulinum Toxin A", "זריקה"),

    # ═══════════════════════════════════════════════════
    # שלפוחית / שתן / גינקולוגיה — Urology / Gynaecology
    # ═══════════════════════════════════════════════════
    ("Betamiga", "Mirabegron", "טבליות"),
    ("Myrbetriq", "Mirabegron", "טבליות"),
    ("Mirabegron", "Mirabegron", "טבליות"),
    ("Vesicare", "Solifenacin", "טבליות"),
    ("Solifenacin", "Solifenacin", "טבליות"),
    ("Detrusitol", "Tolterodine", "כמוסות"),
    ("Tolterodine", "Tolterodine", "כמוסות"),
    ("Enablex", "Darifenacin", "טבליות"),
    ("Toviaz", "Fesoterodine", "טבליות"),
    ("Sanctura", "Trospium", "טבליות"),
    ("Ditropan", "Oxybutynin", "טבליות"),
    ("Oxybutynin", "Oxybutynin", "טבליות"),
    ("Urotrol", "Alfuzosin", "טבליות"),
    ("Uroxatral", "Alfuzosin", "טבליות"),
    ("Flomax", "Tamsulosin", "כמוסות"),
    ("Jalyn", "Dutasteride + Tamsulosin", "כמוסות"),
    ("Combodart", "Dutasteride + Tamsulosin", "כמוסות"),
    ("Pyridium", "Phenazopyridine", "טבליות"),
    ("Macrobid", "Nitrofurantoin", "כמוסות"),
    ("Nitrofurantoin", "Nitrofurantoin", "כמוסות"),
    ("Hiprex", "Methenamine", "טבליות"),

    # ═══════════════════════════════════════════════════
    # כאב עצבי / מיגרנה / כאב כרוני
    # ═══════════════════════════════════════════════════
    ("Cymbalta", "Duloxetine", "כמוסות"),
    ("Savella", "Milnacipran", "טבליות"),
    ("Milnacipran", "Milnacipran", "טבליות"),
    ("Tapentadol", "Tapentadol", "טבליות"),
    ("Palexia", "Tapentadol", "טבליות"),
    ("Nucynta", "Tapentadol", "טבליות"),
    ("Hydromorphone", "Hydromorphone", "טבליות"),
    ("Dilaudid", "Hydromorphone", "טבליות"),
    ("Methadone", "Methadone", "טבליות"),
    ("Pethidine", "Pethidine", "זריקה"),
    ("Codeine", "Codeine", "טבליות"),
    ("Co-Codamol", "Codeine + Paracetamol", "טבליות"),
    ("Zofran", "Ondansetron", "טבליות"),
    ("Maxolon", "Metoclopramide", "טבליות"),
    ("Ergotamine", "Ergotamine", "טבליות"),
    ("Cafergot", "Ergotamine + Caffeine", "טבליות"),
    ("Dihydroergotamine", "Dihydroergotamine", "אינהלר / זריקה"),

    # ═══════════════════════════════════════════════════
    # גסטרואנטרולוגיה נוספות
    # ═══════════════════════════════════════════════════
    ("Creon", "Pancreatin", "כמוסות"),
    ("Pancreatin", "Pancreatin", "כמוסות"),
    ("Questran", "Cholestyramine", "אבקה"),
    ("Cholestyramine", "Cholestyramine", "אבקה"),
    ("Colestid", "Colestipol", "גרגירים"),
    ("Sucralfate", "Sucralfate", "טבליות / תרחיף"),
    ("Carafate", "Sucralfate", "טבליות"),
    ("Misoprostol", "Misoprostol", "טבליות"),
    ("Cytotec", "Misoprostol", "טבליות"),
    ("Domperidone", "Domperidone", "טבליות"),
    ("Erythromycin", "Erythromycin", "טבליות / קפסולות"),
    ("Senna", "Senna", "טבליות"),
    ("Senokot", "Senna", "טבליות"),
    ("Bisacodyl", "Bisacodyl", "טבליות / סופוזיטוריה"),
    ("Normacol", "Sterculia", "גרגירים"),
    ("Psyllium", "Psyllium Husk", "אבקה"),
    ("Konsyl", "Psyllium", "אבקה"),
    ("Methylcellulose", "Methylcellulose", "אבקה"),
    ("Tinidazole", "Tinidazole", "טבליות"),
    ("Fasigyn", "Tinidazole", "טבליות"),
    ("Vancomycin oral", "Vancomycin", "כמוסות"),
    ("Fidaxomicin", "Fidaxomicin", "טבליות"),
    ("Dificid", "Fidaxomicin", "טבליות"),
    ("Eluxadoline", "Eluxadoline", "טבליות"),
    ("Viberzi", "Eluxadoline", "טבליות"),
    ("Linaclotide", "Linaclotide", "כמוסות"),
    ("Linzess", "Linaclotide", "כמוסות"),
    ("Lubiprostone", "Lubiprostone", "כמוסות"),
    ("Amitiza", "Lubiprostone", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # נשימה / ריאות נוספות
    # ═══════════════════════════════════════════════════
    ("Singulair", "Montelukast", "טבליות"),
    ("Zafirlukast", "Zafirlukast", "טבליות"),
    ("Accolate", "Zafirlukast", "טבליות"),
    ("Zileuton", "Zileuton", "טבליות"),
    ("Caffeine citrate", "Caffeine", "תמיסה"),
    ("Doxapram", "Doxapram", "עירוי"),
    ("Acetylcysteine", "Acetylcysteine", "אבקה / תמיסה"),
    ("ACC", "Acetylcysteine", "אבקה"),
    ("Mucosolvan", "Ambroxol", "תמיסה / טבליות"),
    ("Ambroxol", "Ambroxol", "תמיסה"),
    ("Bromhexine", "Bromhexine", "טבליות"),
    ("Bisolvon", "Bromhexine", "טבליות"),
    ("Guaifenesin", "Guaifenesin", "תמיסה"),
    ("Robitussin", "Guaifenesin", "תמיסה"),
    ("Dextromethorphan", "Dextromethorphan", "תמיסה"),
    ("Sudafed", "Pseudoephedrine", "טבליות"),
    ("Pseudoephedrine", "Pseudoephedrine", "טבליות"),
    ("Xyzal", "Levocetirizine", "טבליות"),
    ("Levocetirizine", "Levocetirizine", "טבליות"),
    ("Bilaxten", "Bilastine", "טבליות"),
    ("Bilastine", "Bilastine", "טבליות"),
    ("Rupatadine", "Rupatadine", "טבליות"),
    ("Rupafin", "Rupatadine", "טבליות"),
    ("Avamys", "Fluticasone Furoate", "תרסיס לאף"),
    ("Nasonex", "Mometasone", "תרסיס לאף"),
    ("Mometasone", "Mometasone", "תרסיס לאף"),
    ("Beconase", "Beclomethasone nasal", "תרסיס לאף"),
    ("Rhinocort", "Budesonide nasal", "תרסיס לאף"),
    ("Teva-Rhinocort", "Budesonide nasal", "תרסיס לאף"),
    ("Azelastine", "Azelastine", "תרסיס לאף"),
    ("Dymista", "Azelastine + Fluticasone", "תרסיס לאף"),
    ("Ipratropium nasal", "Ipratropium", "תרסיס לאף"),
    ("Otrivin", "Xylometazoline", "טיפות אף"),
    ("Xylometazoline", "Xylometazoline", "טיפות אף"),
    ("Oxymetazoline", "Oxymetazoline", "טיפות אף"),
    ("Africin", "Oxymetazoline", "טיפות אף"),

    # ═══════════════════════════════════════════════════
    # אנטיביוטיקה נוספת
    # ═══════════════════════════════════════════════════
    ("Penicillin V", "Phenoxymethylpenicillin", "טבליות"),
    ("Phenoxymethylpenicillin", "Phenoxymethylpenicillin", "טבליות"),
    ("Ampicillin", "Ampicillin", "כמוסות / זריקה"),
    ("Ampiclox", "Ampicillin + Cloxacillin", "כמוסות"),
    ("Cloxacillin", "Cloxacillin", "כמוסות"),
    ("Dicloxacillin", "Dicloxacillin", "כמוסות"),
    ("Flucloxacillin", "Flucloxacillin", "כמוסות"),
    ("Cefadroxil", "Cefadroxil", "כמוסות"),
    ("Duracef", "Cefadroxil", "כמוסות"),
    ("Cefprozil", "Cefprozil", "טבליות"),
    ("Cefdinir", "Cefdinir", "כמוסות"),
    ("Omnicef", "Cefdinir", "כמוסות"),
    ("Cefixime", "Cefixime", "טבליות"),
    ("Suprax", "Cefixime", "טבליות"),
    ("Cefpodoxime", "Cefpodoxime", "טבליות"),
    ("Orelox", "Cefpodoxime", "טבליות"),
    ("Meropenem", "Meropenem", "עירוי"),
    ("Imipenem", "Imipenem + Cilastatin", "עירוי"),
    ("Ertapenem", "Ertapenem", "עירוי"),
    ("Invanz", "Ertapenem", "עירוי"),
    ("Piperacillin-Tazobactam", "Piperacillin + Tazobactam", "עירוי"),
    ("Tazocin", "Piperacillin + Tazobactam", "עירוי"),
    ("Colistin", "Colistimethate", "עירוי"),
    ("Polymyxin B", "Polymyxin B", "עירוי"),
    ("Fosfomycin", "Fosfomycin", "אבקה"),
    ("Monurol", "Fosfomycin", "אבקה"),
    ("Nitrofurantoin", "Nitrofurantoin", "כמוסות"),
    ("Trimethoprim", "Trimethoprim", "טבליות"),
    ("Erythromycin", "Erythromycin", "טבליות"),
    ("Roxithromycin", "Roxithromycin", "טבליות"),
    ("Rulide", "Roxithromycin", "טבליות"),
    ("Spiramycin", "Spiramycin", "טבליות"),
    ("Rovamycine", "Spiramycin", "טבליות"),
    ("Telithromycin", "Telithromycin", "טבליות"),
    ("Ketek", "Telithromycin", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה נוספות / כאב עצבי
    # ═══════════════════════════════════════════════════
    ("Mexiletine", "Mexiletine", "כמוסות"),
    ("Mexitil", "Mexiletine", "כמוסות"),
    ("Flupirtine", "Flupirtine", "כמוסות"),
    ("Catapres", "Clonidine", "טבליות / מדבקה"),
    ("Tenex", "Guanfacine", "טבליות"),
    ("Guanfacine", "Guanfacine", "טבליות"),
    ("Memantine", "Memantine", "טבליות"),
    ("Namenda", "Memantine", "טבליות"),
    ("Riluzole", "Riluzole", "טבליות"),
    ("Rilutek", "Riluzole", "טבליות"),
    ("Edaravone", "Edaravone", "עירוי"),
    ("Radicava", "Edaravone", "עירוי"),
    ("Nusinersen", "Nusinersen", "זריקה לעמוד שדרה"),
    ("Spinraza", "Nusinersen", "זריקה לעמוד שדרה"),
    ("Risdiplam", "Risdiplam", "תמיסה"),
    ("Evrysdi", "Risdiplam", "תמיסה"),
    ("Onasemnogene", "Onasemnogene abeparvovec", "עירוי"),
    ("Zolgensma", "Onasemnogene abeparvovec", "עירוי"),
    ("Idebenone", "Idebenone", "טבליות"),
    ("Raxone", "Idebenone", "טבליות"),
    ("Deutetrabenazine", "Deutetrabenazine", "טבליות"),
    ("Austedo", "Deutetrabenazine", "טבליות"),
    ("Tetrabenazine", "Tetrabenazine", "טבליות"),
    ("Nitoman", "Tetrabenazine", "טבליות"),
    ("Valbenazine", "Valbenazine", "כמוסות"),
    ("Ingrezza", "Valbenazine", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # עור ועיניים — Dermatology / Ophthalmology
    # ═══════════════════════════════════════════════════
    ("Tretinoin", "Tretinoin", "קרם / ג'ל"),
    ("Retin-A", "Tretinoin", "קרם"),
    ("Adapalene", "Adapalene", "ג'ל"),
    ("Differin", "Adapalene", "ג'ל"),
    ("Tazarotene", "Tazarotene", "קרם / ג'ל"),
    ("Tazorac", "Tazarotene", "קרם"),
    ("Benzoyl Peroxide", "Benzoyl Peroxide", "ג'ל / קרם"),
    ("Brevoxyl", "Benzoyl Peroxide", "ג'ל"),
    ("Clindamycin topical", "Clindamycin", "ג'ל / תמיסה"),
    ("Dalacin T", "Clindamycin topical", "תמיסה"),
    ("Erythromycin topical", "Erythromycin", "ג'ל"),
    ("Dapsone", "Dapsone", "ג'ל"),
    ("Aczone", "Dapsone", "ג'ל"),
    ("Azelaic acid", "Azelaic Acid", "קרם / ג'ל"),
    ("Finacea", "Azelaic Acid", "ג'ל"),
    ("Ivermectin topical", "Ivermectin", "קרם"),
    ("Soolantra", "Ivermectin topical", "קרם"),
    ("Metronidazole topical", "Metronidazole", "קרם / ג'ל"),
    ("Rozex", "Metronidazole topical", "קרם"),
    ("Calcipotriol", "Calcipotriol", "קרם / תמיסה"),
    ("Daivonex", "Calcipotriol", "קרם"),
    ("Dovobet", "Calcipotriol + Betamethasone", "ג'ל"),
    ("Enstilar", "Calcipotriol + Betamethasone", "קצף"),
    ("Tacrolimus topical", "Tacrolimus", "משחה"),
    ("Protopic", "Tacrolimus topical", "משחה"),
    ("Pimecrolimus", "Pimecrolimus", "קרם"),
    ("Elidel", "Pimecrolimus", "קרם"),
    ("Crisaborole", "Crisaborole", "משחה"),
    ("Eucrisa", "Crisaborole", "משחה"),
    ("Ruxolitinib cream", "Ruxolitinib", "קרם"),
    ("Opzelura", "Ruxolitinib cream", "קרם"),
    ("Abrocitinib", "Abrocitinib", "טבליות"),
    ("Cibinqo", "Abrocitinib", "טבליות"),
    ("Lebrikizumab", "Lebrikizumab", "זריקה"),
    ("Ebglyss", "Lebrikizumab", "זריקה"),
    ("Tralokinumab", "Tralokinumab", "זריקה"),
    ("Adbry", "Tralokinumab", "זריקה"),
    ("Apremilast", "Apremilast", "טבליות"),
    ("Otezla", "Apremilast", "טבליות"),
    ("Secukinumab", "Secukinumab", "זריקה"),
    ("Ixekizumab", "Ixekizumab", "זריקה"),
    ("Bimekizumab", "Bimekizumab", "זריקה"),
    ("Bimzelx", "Bimekizumab", "זריקה"),
    ("Spesolimab", "Spesolimab", "עירוי"),
    ("Spevigo", "Spesolimab", "עירוי"),
    # עיניים
    ("Latanoprost", "Latanoprost", "טיפות עיניים"),
    ("Travoprost", "Travoprost", "טיפות עיניים"),
    ("Travatan", "Travoprost", "טיפות עיניים"),
    ("Bimatoprost", "Bimatoprost", "טיפות עיניים"),
    ("Tafluprost", "Tafluprost", "טיפות עיניים"),
    ("Saflutan", "Tafluprost", "טיפות עיניים"),
    ("Brimonidine", "Brimonidine", "טיפות עיניים"),
    ("Alphagan", "Brimonidine", "טיפות עיניים"),
    ("Brinzolamide", "Brinzolamide", "טיפות עיניים"),
    ("Azopt", "Brinzolamide", "טיפות עיניים"),
    ("Dorzolamide", "Dorzolamide", "טיפות עיניים"),
    ("Trusopt", "Dorzolamide", "טיפות עיניים"),
    ("Netarsudil", "Netarsudil", "טיפות עיניים"),
    ("Rhopressa", "Netarsudil", "טיפות עיניים"),
    ("Latanoprostene", "Latanoprostene bunod", "טיפות עיניים"),
    ("Vyzulta", "Latanoprostene bunod", "טיפות עיניים"),
    ("Cyclosporine eye", "Cyclosporine", "טיפות עיניים"),
    ("Restasis", "Cyclosporine eye", "טיפות עיניים"),
    ("Lifitegrast", "Lifitegrast", "טיפות עיניים"),
    ("Xiidra", "Lifitegrast", "טיפות עיניים"),
    ("Ikervis", "Cyclosporine", "טיפות עיניים"),
    ("Loteprednol", "Loteprednol", "טיפות עיניים"),
    ("Lotemax", "Loteprednol", "טיפות עיניים"),
    ("Prednisolone eye", "Prednisolone", "טיפות עיניים"),
    ("Dexamethasone eye", "Dexamethasone", "טיפות עיניים"),
    ("Maxidex", "Dexamethasone eye", "טיפות עיניים"),
    ("Tobramycin", "Tobramycin", "טיפות עיניים / משחה"),
    ("Tobrex", "Tobramycin", "טיפות עיניים"),
    ("Chloramphenicol eye", "Chloramphenicol", "טיפות עיניים"),
    ("Sodium hyaluronate", "Sodium Hyaluronate", "טיפות עיניים"),
    ("Hyal-Drop", "Sodium Hyaluronate", "טיפות עיניים"),
    ("Hyabak", "Sodium Hyaluronate", "טיפות עיניים"),
    ("Artifical Tears", "Carboxymethylcellulose", "טיפות עיניים"),
    ("Systane", "Polyethylene Glycol", "טיפות עיניים"),
    ("Refresh", "Carboxymethylcellulose", "טיפות עיניים"),
    ("Pilocarpine eye", "Pilocarpine", "טיפות עיניים"),
    ("Atropine eye", "Atropine", "טיפות עיניים"),
    ("Ranibizumab", "Ranibizumab", "זריקה תוך-עינית"),
    ("Bevacizumab", "Bevacizumab", "זריקה תוך-עינית"),
    ("Faricimab", "Faricimab", "זריקה תוך-עינית"),
    ("Vabysmo", "Faricimab", "זריקה תוך-עינית"),

    # ═══════════════════════════════════════════════════
    # המטולוגיה / אנמיה / קרישה
    # ═══════════════════════════════════════════════════
    ("Eltrombopag", "Eltrombopag", "טבליות"),
    ("Revolade", "Eltrombopag", "טבליות"),
    ("Promacta", "Eltrombopag", "טבליות"),
    ("Romiplostim", "Romiplostim", "זריקה"),
    ("Nplate", "Romiplostim", "זריקה"),
    ("Avatrombopag", "Avatrombopag", "טבליות"),
    ("Doptelet", "Avatrombopag", "טבליות"),
    ("Lusutrombopag", "Lusutrombopag", "טבליות"),
    ("Mulpleta", "Lusutrombopag", "טבליות"),
    ("Tranexamic Acid", "Tranexamic Acid", "טבליות / זריקה"),
    ("Cyklokapron", "Tranexamic Acid", "טבליות"),
    ("Hemostop", "Tranexamic Acid", "טבליות"),
    ("Desmopressin", "Desmopressin", "טיפות / תרסיס / זריקה"),
    ("Minirin", "Desmopressin", "טיפות / תרסיס"),
    ("Deferasirox", "Deferasirox", "טבליות"),
    ("Exjade", "Deferasirox", "טבליות"),
    ("Jadenu", "Deferasirox", "טבליות"),
    ("Deferiprone", "Deferiprone", "טבליות"),
    ("Ferriprox", "Deferiprone", "טבליות"),
    ("Deferoxamine", "Deferoxamine", "זריקה"),
    ("Desferal", "Deferoxamine", "זריקה"),
    ("Erythropoietin", "Epoetin Alfa", "זריקה"),
    ("Eprex", "Epoetin Alfa", "זריקה"),
    ("Neorecormon", "Epoetin Beta", "זריקה"),
    ("Retacrit", "Epoetin Zeta", "זריקה"),
    ("Sirolimus", "Sirolimus", "טבליות"),
    ("Rapamune", "Sirolimus", "טבליות"),
    ("Everolimus", "Everolimus", "טבליות"),
    ("Certican", "Everolimus", "טבליות"),
    ("Afinitor", "Everolimus", "טבליות"),
    ("Hydroxycarbamide", "Hydroxyurea", "כמוסות"),
    ("Siklos", "Hydroxyurea", "טבליות"),
    ("Crizanlizumab", "Crizanlizumab", "עירוי"),
    ("Adakveo", "Crizanlizumab", "עירוי"),
    ("Voxelotor", "Voxelotor", "טבליות"),
    ("Oxbryta", "Voxelotor", "טבליות"),
    ("L-Glutamine", "L-Glutamine", "אבקה"),
    ("Endari", "L-Glutamine", "אבקה"),

    # ═══════════════════════════════════════════════════
    # אנדוקרינולוגיה / מטבוליזם
    # ═══════════════════════════════════════════════════
    ("Fludrocortisone", "Fludrocortisone", "טבליות"),
    ("Florinef", "Fludrocortisone", "טבליות"),
    ("Octreotide", "Octreotide", "זריקה"),
    ("Lanreotide", "Lanreotide", "זריקה"),
    ("Somatuline", "Lanreotide", "זריקה"),
    ("Pasireotide", "Pasireotide", "זריקה"),
    ("Signifor", "Pasireotide", "זריקה"),
    ("Cabergoline", "Cabergoline", "טבליות"),
    ("Dostinex", "Cabergoline", "טבליות"),
    ("Bromocriptine", "Bromocriptine", "טבליות"),
    ("Parlodel", "Bromocriptine", "טבליות"),
    ("Pegvisomant", "Pegvisomant", "זריקה"),
    ("Somavert", "Pegvisomant", "זריקה"),
    ("Somatropin", "Somatropin", "זריקה"),
    ("Norditropin", "Somatropin", "זריקה"),
    ("Genotropin", "Somatropin", "זריקה"),
    ("Humatrope", "Somatropin", "זריקה"),
    ("Metyrapone", "Metyrapone", "כמוסות"),
    ("Metopirone", "Metyrapone", "כמוסות"),
    ("Osilodrostat", "Osilodrostat", "טבליות"),
    ("Isturisa", "Osilodrostat", "טבליות"),
    ("Mifepristone", "Mifepristone", "טבליות"),
    ("Korlym", "Mifepristone", "טבליות"),
    ("Cinacalcet", "Cinacalcet", "טבליות"),
    ("Mimpara", "Cinacalcet", "טבליות"),
    ("Etelcalcetide", "Etelcalcetide", "זריקה"),
    ("Parsabiv", "Etelcalcetide", "זריקה"),
    ("Burosumab", "Burosumab", "זריקה"),
    ("Crysvita", "Burosumab", "זריקה"),
    ("Carglumi acid", "Carglumic Acid", "טבליות"),
    ("Carbaglu", "Carglumic Acid", "טבליות"),
    ("Nitisinone", "Nitisinone", "כמוסות"),
    ("Orfadin", "Nitisinone", "כמוסות"),
    ("Sapropterin", "Sapropterin", "טבליות"),
    ("Kuvan", "Sapropterin", "טבליות"),
    ("Miglustat", "Miglustat", "כמוסות"),
    ("Zavesca", "Miglustat", "כמוסות"),
    ("Eliglustat", "Eliglustat", "כמוסות"),
    ("Cerdelga", "Eliglustat", "כמוסות"),
    ("Imiglucerase", "Imiglucerase", "עירוי"),
    ("Cerezyme", "Imiglucerase", "עירוי"),
    ("Velaglucerase", "Velaglucerase", "עירוי"),
    ("VPRIV", "Velaglucerase", "עירוי"),
    ("Taliglucerase", "Taliglucerase", "עירוי"),
    ("Elelyso", "Taliglucerase", "עירוי"),

    # ═══════════════════════════════════════════════════
    # ראומטולוגיה / עצמות נוספות
    # ═══════════════════════════════════════════════════
    ("Denosumab", "Denosumab", "זריקה"),
    ("Xgeva", "Denosumab", "זריקה"),
    ("Zoledronic Acid", "Zoledronic Acid", "עירוי"),
    ("Zometa", "Zoledronic Acid", "עירוי"),
    ("Reclast", "Zoledronic Acid", "עירוי"),
    ("Pamidronate", "Pamidronate", "עירוי"),
    ("Aredia", "Pamidronate", "עירוי"),
    ("Clodronate", "Clodronate", "טבליות / עירוי"),
    ("Bonefos", "Clodronate", "כמוסות"),
    ("Etidronate", "Etidronate", "טבליות"),
    ("Didronel", "Etidronate", "טבליות"),
    ("Anakinra", "Anakinra", "זריקה"),
    ("Kineret", "Anakinra", "זריקה"),
    ("Canakinumab", "Canakinumab", "זריקה"),
    ("Ilaris", "Canakinumab", "זריקה"),
    ("Rilonacept", "Rilonacept", "זריקה"),
    ("Arcalyst", "Rilonacept", "זריקה"),
    ("Secukinumab", "Secukinumab", "זריקה"),
    ("Ixekizumab", "Ixekizumab", "זריקה"),
    ("Bimekizumab", "Bimekizumab", "זריקה"),
    ("Brodalumab", "Brodalumab", "זריקה"),
    ("Siliq", "Brodalumab", "זריקה"),
    ("Spesolimab", "Spesolimab", "עירוי"),
    ("Deucravacitinib", "Deucravacitinib", "טבליות"),
    ("Sotyktu", "Deucravacitinib", "טבליות"),
    ("Filgotinib", "Filgotinib", "טבליות"),
    ("Jyseleca", "Filgotinib", "טבליות"),
    ("Pegloticase", "Pegloticase", "עירוי"),
    ("Krystexxa", "Pegloticase", "עירוי"),
    ("Rasburicase", "Rasburicase", "עירוי"),
    ("Fasturtec", "Rasburicase", "עירוי"),

    # ═══════════════════════════════════════════════════
    # ילדים ופגים — Paediatrics
    # ═══════════════════════════════════════════════════
    ("Caffeine citrate", "Caffeine Citrate", "תמיסה"),
    ("Peyona", "Caffeine Citrate", "תמיסה"),
    ("Surfactant", "Poractant Alfa", "תוך-קנה"),
    ("Curosurf", "Poractant Alfa", "תוך-קנה"),
    ("Survanta", "Beractant", "תוך-קנה"),
    ("Ibuprofen IV", "Ibuprofen", "עירוי"),
    ("Pedea", "Ibuprofen IV", "עירוי"),
    ("Indomethacin IV", "Indomethacin", "עירוי"),
    ("Indocid IV", "Indomethacin", "עירוי"),
    ("Alprostadil", "Alprostadil", "עירוי"),
    ("Prostavasin", "Alprostadil", "עירוי"),
    ("Sildenafil IV", "Sildenafil", "עירוי"),
    ("Bosentan", "Bosentan", "טבליות"),
    ("Tracleer", "Bosentan", "טבליות"),
    ("Ambrisentan", "Ambrisentan", "טבליות"),
    ("Volibris", "Ambrisentan", "טבליות"),
    ("Macitentan", "Macitentan", "טבליות"),
    ("Opsumit", "Macitentan", "טבליות"),
    ("Selexipag", "Selexipag", "טבליות"),
    ("Uptravi", "Selexipag", "טבליות"),
    ("Iloprost", "Iloprost", "אינהלציה"),
    ("Ventavis", "Iloprost", "אינהלציה"),
    ("Treprostinil", "Treprostinil", "עירוי / אינהלציה"),
    ("Remodulin", "Treprostinil", "עירוי"),
    ("Epoprostenol", "Epoprostenol", "עירוי"),
    ("Flolan", "Epoprostenol", "עירוי"),
    ("Riociguat", "Riociguat", "טבליות"),
    ("Adempas", "Riociguat", "טבליות"),
    ("Vericiguat", "Vericiguat", "טבליות"),
    ("Verquvo", "Vericiguat", "טבליות"),

    # ═══════════════════════════════════════════════════
    # שיכוך כאב / הרדמה
    # ═══════════════════════════════════════════════════
    ("Ketamine", "Ketamine", "תמיסה / זריקה"),
    ("Ketalar", "Ketamine", "זריקה"),
    ("Propofol", "Propofol", "עירוי"),
    ("Diprivan", "Propofol", "עירוי"),
    ("Midazolam", "Midazolam", "זריקה / תמיסה"),
    ("Dormicum", "Midazolam", "זריקה"),
    ("Fentanyl IV", "Fentanyl", "זריקה / עירוי"),
    ("Naloxone", "Naloxone", "זריקה / תרסיס לאף"),
    ("Narcan", "Naloxone", "תרסיס לאף"),
    ("Naltrexone", "Naltrexone", "טבליות"),
    ("Nalorex", "Naltrexone", "טבליות"),
    ("Buprenorphine sublingual", "Buprenorphine", "תת-לשוני"),
    ("Subutex", "Buprenorphine", "תת-לשוני"),
    ("Suboxone", "Buprenorphine + Naloxone", "תת-לשוני"),
    ("Lidocaine", "Lidocaine", "תמיסה / קרם"),
    ("Xylocaine", "Lidocaine", "תמיסה"),
    ("Bupivacaine", "Bupivacaine", "זריקה"),
    ("Marcain", "Bupivacaine", "זריקה"),
    ("Ropivacaine", "Ropivacaine", "זריקה"),
    ("Naropin", "Ropivacaine", "זריקה"),
    ("Mepivacaine", "Mepivacaine", "זריקה"),
    ("Scandonest", "Mepivacaine", "זריקה"),

    # ═══════════════════════════════════════════════════
    # חיסונים ואימונוגלובולינים
    # ═══════════════════════════════════════════════════
    ("IVIG", "Immunoglobulin IV", "עירוי"),
    ("Privigen", "Immunoglobulin IV", "עירוי"),
    ("Gamunex", "Immunoglobulin IV", "עירוי"),
    ("Subcuvia", "Immunoglobulin SC", "תת-עורי"),
    ("Hyqvia", "Immunoglobulin SC", "תת-עורי"),
    ("Omalizumab", "Omalizumab", "זריקה"),
    ("Canakinumab", "Canakinumab", "זריקה"),
    ("Rho(D) Immunoglobulin", "Anti-D", "זריקה"),
    ("WinRho", "Anti-D", "זריקה"),
    ("Tetanus Immunoglobulin", "Tetanus IG", "זריקה"),
    ("Rabies Immunoglobulin", "Rabies IG", "זריקה"),
    ("Hepatitis B IG", "Hepatitis B Immunoglobulin", "זריקה"),
    ("Palivizumab", "Palivizumab", "זריקה"),
    ("Synagis", "Palivizumab", "זריקה"),
    ("Nirsevimab", "Nirsevimab", "זריקה"),
    ("Beyfortus", "Nirsevimab", "זריקה"),

    # ═══════════════════════════════════════════════════
    # מחלות נדירות ומחלות מטבוליות
    # ═══════════════════════════════════════════════════
    ("Laronidase", "Laronidase", "עירוי"),
    ("Aldurazyme", "Laronidase", "עירוי"),
    ("Idursulfase", "Idursulfase", "עירוי"),
    ("Elaprase", "Idursulfase", "עירוי"),
    ("Galsulfase", "Galsulfase", "עירוי"),
    ("Naglazyme", "Galsulfase", "עירוי"),
    ("Agalsidase beta", "Agalsidase Beta", "עירוי"),
    ("Fabrazyme", "Agalsidase Beta", "עירוי"),
    ("Agalsidase alfa", "Agalsidase Alfa", "עירוי"),
    ("Replagal", "Agalsidase Alfa", "עירוי"),
    ("Migalastat", "Migalastat", "כמוסות"),
    ("Galafold", "Migalastat", "כמוסות"),
    ("Sebelipase alfa", "Sebelipase Alfa", "עירוי"),
    ("Kanuma", "Sebelipase Alfa", "עירוי"),
    ("Asfotase alfa", "Asfotase Alfa", "זריקה"),
    ("Strensiq", "Asfotase Alfa", "זריקה"),
    ("Vestronidase alfa", "Vestronidase Alfa", "עירוי"),
    ("Mepsevii", "Vestronidase Alfa", "עירוי"),
    ("Cerliponase alfa", "Cerliponase Alfa", "תוך-מוחי"),
    ("Brineura", "Cerliponase Alfa", "תוך-מוחי"),
    ("Olipudase alfa", "Olipudase Alfa", "עירוי"),
    ("Xenpozyme", "Olipudase Alfa", "עירוי"),
    ("Avalglucosidase alfa", "Avalglucosidase Alfa", "עירוי"),
    ("Nexviazyme", "Avalglucosidase Alfa", "עירוי"),
    ("Alglucosidase alfa", "Alglucosidase Alfa", "עירוי"),
    ("Myozyme", "Alglucosidase Alfa", "עירוי"),
    ("Lumizyme", "Alglucosidase Alfa", "עירוי"),
    ("Cipaglucosidase alfa", "Cipaglucosidase Alfa", "עירוי"),
    ("Pombiliti", "Cipaglucosidase Alfa", "עירוי"),

    # ═══════════════════════════════════════════════════
    # כלי דם / לחץ דם נוסף
    # ═══════════════════════════════════════════════════
    ("Hydralazine", "Hydralazine", "טבליות"),
    ("Nitroprusside", "Sodium Nitroprusside", "עירוי"),
    ("Nipride", "Sodium Nitroprusside", "עירוי"),
    ("Fenoldopam", "Fenoldopam", "עירוי"),
    ("Labetalol", "Labetalol", "טבליות / עירוי"),
    ("Trandate", "Labetalol", "טבליות"),
    ("Phentolamine", "Phentolamine", "זריקה"),
    ("Regitine", "Phentolamine", "זריקה"),
    ("Prazosin", "Prazosin", "טבליות"),
    ("Minipress", "Prazosin", "טבליות"),
    ("Terazosin", "Terazosin", "טבליות"),
    ("Hytrin", "Terazosin", "טבליות"),
    ("Minoxidil oral", "Minoxidil", "טבליות"),
    ("Minoxidil topical", "Minoxidil", "תמיסה / קצף"),
    ("Rogaine", "Minoxidil", "תמיסה"),
    ("Sacubitril", "Sacubitril + Valsartan", "טבליות"),
    ("Finerenone", "Finerenone", "טבליות"),
    ("Empagliflozin + Metformin", "Empagliflozin + Metformin", "טבליות"),
    ("Synjardy", "Empagliflozin + Metformin", "טבליות"),
    ("Dapagliflozin + Metformin", "Dapagliflozin + Metformin", "טבליות"),
    ("Xigduo", "Dapagliflozin + Metformin", "טבליות"),

    # ═══════════════════════════════════════════════════
    # אוזניים / א.א.ג — ENT
    # ═══════════════════════════════════════════════════
    ("Ciprofloxacin otic", "Ciprofloxacin", "טיפות אוזניים"),
    ("Ciprodex", "Ciprofloxacin + Dexamethasone", "טיפות אוזניים"),
    ("Sofradex", "Framycetin + Dexamethasone", "טיפות אוזניים"),
    ("Otomize", "Dexamethasone + Glacial Acetic Acid", "טיפות אוזניים"),
    ("Cerumol", "Chlorobutanol", "טיפות אוזניים"),
    ("Earex", "Arachis Oil", "טיפות אוזניים"),
    ("Betahistine", "Betahistine", "טבליות"),
    ("Serc", "Betahistine", "טבליות"),
    ("Cinnarizine", "Cinnarizine", "טבליות"),
    ("Stugeron", "Cinnarizine", "טבליות"),
    ("Meclizine", "Meclizine", "טבליות"),
    ("Antivert", "Meclizine", "טבליות"),
    ("Prochlorperazine", "Prochlorperazine", "טבליות / זריקה"),
    ("Stemetil", "Prochlorperazine", "טבליות"),
    ("Droperidol", "Droperidol", "זריקה"),
    ("Scopolamine", "Scopolamine", "מדבקה"),
    ("Scopoderm", "Scopolamine", "מדבקה"),
    ("Dimenhydrinate", "Dimenhydrinate", "טבליות"),
    ("Dramamine", "Dimenhydrinate", "טבליות"),
    ("Promethazine", "Promethazine", "טבליות / זריקה"),
    ("Phenergan", "Promethazine", "טבליות"),
]
