"""
רשימת תרופות מורחבת לשימוש במערכת מנהל האירוע הרפואי.
פורמט: (שם_מסחרי, שם_גנרי, צורת_מתן)
"""

# שם מסחרי (אנגלי) → שם עברי נפוץ
HEBREW_NAMES: dict[str, str] = {
    # כאב / חום
    "Acamol": "אקמול", "Optalgin": "אופטלגין", "Ibufen": "איבופן",
    "Advil": "אדוויל", "Voltaren": "וולטרן", "Arcoxia": "ארקוקסיה",
    "Tramadex": "טרמדקס", "Tramadol": "טרמדול",
    # לחץ דם / לב
    "Concor": "קונקור", "Norvasc": "נורוואסק", "Amlopin": "אמלופין",
    "Tritace": "טריטייס", "Coversyl": "קוברסיל", "Zestril": "זסטריל",
    "Lasix": "לאסיקס", "Aldactone": "אלדקטון", "Cordarone": "קורדרון",
    "Digoxin": "דיגוקסין", "Lanoxin": "לנוקסין", "Entresto": "אנטרסטו",
    "Procoralan": "פרוקורלן",
    # נוגדי קרישה / אנטי-טסיות
    "Coumadin": "קומדין", "Plavix": "פלביקס", "Xarelto": "קסרלטו",
    "Eliquis": "אליקויס", "Pradaxa": "פרדקסה", "Clexane": "קלקסיין",
    "Brilique": "ברילינטה",
    # כולסטרול
    "Lipitor": "ליפיטור", "Crestor": "קרסטור", "Zocor": "זוקור",
    "Ezetrol": "אזטרול", "Inegy": "אינגי",
    # סוכרת
    "Glucophage": "גלוקופאג'", "Januvia": "ג'נוויה", "Jardiance": "ג'ארדיאנס",
    "Forxiga": "פורקסיגה", "Ozempic": "אוזמפיק", "Victoza": "ויקטוזה",
    "Trulicity": "טרוליסיטי", "Lantus": "לנטוס", "Novorapid": "נוברפיד",
    "Humalog": "הומלוג", "Tresiba": "טרסיבה", "Levemir": "לבמיר",
    "Toujeo": "טוג'יאו", "Rybelsus": "ריבלסוס",
    # בלוטת תריס
    "Eltroxin": "אלטרוקסין", "Euthyrox": "אוטירוקס",
    # נוירולוגיה
    "Tegretol": "טגרטול", "Depakine": "דפאקין", "Lamictal": "לאמיקטל",
    "Keppra": "קפרה", "Topamax": "טופמקס", "Rivotril": "ריבוטריל",
    "Neurontin": "נוירונטין", "Lyrica": "ליריקה",
    # פרקינסון
    "Madopar": "מאדופר", "Sinemet": "סינמט", "Azilect": "אזילקט",
    "Rasagiline": "רסגילין",
    # MS
    "Copaxone": "קופקסון", "Gilenya": "ג'ילניה", "Tecfidera": "טקפידרה",
    "Tysabri": "טיסברי", "Ocrevus": "אוקרבוס",
    # דמנציה
    "Aricept": "אריספט", "Exelon": "אקסלון", "Ebixa": "אביקסה",
    # פסיכיאטריה
    "Cipralex": "ציפרלקס", "Prozac": "פרוזק", "Zoloft": "זולופט",
    "Effexor": "אפקסור", "Cymbalta": "סימבלטה", "Remeron": "רמרון",
    "Xanax": "קסנקס", "Rivotril": "ריבוטריל", "Stilnox": "סטילנוקס",
    "Risperdal": "ריספרדל", "Zyprexa": "זיפרקסה", "Seroquel": "סרוקוול",
    "Abilify": "אביליפיי", "Haldol": "הלדול",
    # ADHD
    "Ritalin": "ריטאלין", "Concerta": "קונצרטה",
    # ריאות
    "Ventolin": "ונטולין", "Spiriva": "ספיריבה", "Symbicort": "סימביקורט",
    "Seretide": "סרטייד", "Flixotide": "פליקסוטייד",
    "Singulair": "סינגולייר", "Montelukast": "מונטלוקסט",
    "Xolair": "זולייר", "Dupixent": "דופיקסנט",
    # קיבה
    "Losec": "לוסק", "Nexium": "נקסיום", "Controloc": "קונטרולוק",
    "Primpiran": "פרימפרן", "Motilium": "מוטיליום",
    "Pentasa": "פנטסה", "Mezavant": "מזוונט",
    # אלרגיה
    "Clarityn": "קלריטין", "Zyrtec": "זירטק", "Aerius": "אריוס",
    # אוסטאופורוזיס
    "Fosamax": "פוסאמקס", "Prolia": "פרוליה", "Bonviva": "בונויבה",
    "Evenity": "אוונייטי",
    # אנטיביוטיקה
    "Augmentin": "אוגמנטין", "Zithromax": "זיתרומקס", "Klacid": "קלאסיד",
    "Ciprobay": "ציפרובי", "Tavanic": "טוואניק", "Bactrim": "בקטרים",
    "Flagyl": "פלגיל", "Zinnat": "זינאט",
    # אונקולוגיה
    "Xeloda": "קסלודה", "Taxol": "טקסול", "Taxotere": "טקסוטר",
    "Herceptin": "הרספטין", "Avastin": "אוואסטין", "Keytruda": "קייטרודה",
    "Opdivo": "אופדיבו", "Gleevec": "גליבק", "Tasigna": "טסיניה",
    "Tagrisso": "טגריסו", "Ibrance": "איברנס", "Kisqali": "קיסקלי",
    "Lynparza": "לינפרזה", "Imbruvica": "אימברוויקה",
    "Venclexta": "וונקלקסטה", "Revlimid": "רבלימיד", "Velcade": "וולקייד",
    "Darzalex": "דרזלקס", "Zytiga": "זיטיגה", "Xtandi": "אקסטנדי",
    "Tamoxifen": "טמוקסיפן", "Femara": "פמרה", "Arimidex": "ארימידקס",
    "Zoladex": "זולדקס",
    # ראומטולוגיה
    "Plaquenil": "פלקווניל", "Arava": "ארבה", "Humira": "הומירה",
    "Enbrel": "אנברל", "Remicade": "רמיקייד", "Actemra": "אקטמרה",
    "Rinvoq": "רינבוק", "Xeljanz": "זלג'אנס", "Olumiant": "אולומיאנט",
    "Cosentyx": "קוסנטיקס", "Stelara": "סטלארה", "MabThera": "מבתרה",
    "Imuran": "אימוראן", "CellCept": "סלסמט", "Neoral": "נאורל",
    # שונות
    "Allopurinol": "אלופורינול", "Zyloric": "זילוריק",
    "Colchicine": "קולכיצין", "Colchicum": "קולכיקום",
    "Methotrexate": "מתוטרקסט", "Sildenafil": "סילדנאפיל",
    "Viagra": "ויאגרה", "Cialis": "סיאליס",
    "Vitamin D3": "ויטמין D3", "Vitamin B12": "ויטמין B12",
    "Calcium Carbonate": "סידן", "Folic Acid": "חומצה פולית",
}

DRUGS = [
    # ═══════════════════════════════════════════════════
    # כאב / אנטי-דלקתי / חום
    # ═══════════════════════════════════════════════════
    ("Acamol", "Paracetamol", "טבליות"),
    ("Paracetamol", "Paracetamol", "טבליות"),
    ("Optalgin", "Dipyrone (Metamizole)", "טבליות"),
    ("Dipyrone", "Dipyrone", "טבליות"),
    ("Ibufen", "Ibuprofen", "טבליות"),
    ("Advil", "Ibuprofen", "טבליות"),
    ("Ibuprofen", "Ibuprofen", "טבליות"),
    ("Voltaren", "Diclofenac", "טבליות / ג'ל"),
    ("Diclofenac", "Diclofenac", "טבליות"),
    ("Arcoxia", "Etoricoxib", "טבליות"),
    ("Celebrex", "Celecoxib", "כמוסות"),
    ("Celecoxib", "Celecoxib", "כמוסות"),
    ("Naproxen", "Naproxen", "טבליות"),
    ("Proxen", "Naproxen", "טבליות"),
    ("Indocid", "Indomethacin", "כמוסות"),
    ("Tramadex", "Tramadol", "טבליות"),
    ("Tramadol", "Tramadol", "טבליות"),
    ("Ultram", "Tramadol", "טבליות"),
    ("Zaldiar", "Tramadol + Paracetamol", "טבליות"),
    ("Oxycontin", "Oxycodone", "טבליות"),
    ("Oxycodone", "Oxycodone", "טבליות"),
    ("Norspan", "Buprenorphine", "מדבקה"),
    ("Buprenorphine", "Buprenorphine", "מדבקה / תת-לשונית"),
    ("Fentanyl", "Fentanyl", "מדבקה"),
    ("Durogesic", "Fentanyl", "מדבקה"),
    ("Morphine", "Morphine Sulfate", "טבליות / זריקה"),
    ("Sevredol", "Morphine", "טבליות"),
    ("MST Continus", "Morphine Sulfate CR", "טבליות"),
    ("Lyrica", "Pregabalin", "כמוסות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Neurontin", "Gabapentin", "כמוסות"),
    ("Gabapentin", "Gabapentin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # לב וכלי דם — יתר לחץ דם
    # ═══════════════════════════════════════════════════
    ("Enalapril", "Enalapril", "טבליות"),
    ("Ramipril", "Ramipril", "טבליות"),
    ("Tritace", "Ramipril", "טבליות"),
    ("Lisinopril", "Lisinopril", "טבליות"),
    ("Zestril", "Lisinopril", "טבליות"),
    ("Perindopril", "Perindopril", "טבליות"),
    ("Coversyl", "Perindopril", "טבליות"),
    ("Captopril", "Captopril", "טבליות"),
    ("Losartan", "Losartan", "טבליות"),
    ("Cozaar", "Losartan", "טבליות"),
    ("Valsartan", "Valsartan", "טבליות"),
    ("Diovan", "Valsartan", "טבליות"),
    ("Irbesartan", "Irbesartan", "טבליות"),
    ("Candesartan", "Candesartan", "טבליות"),
    ("Olmesartan", "Olmesartan", "טבליות"),
    ("Concor", "Bisoprolol", "טבליות"),
    ("Bisoprolol", "Bisoprolol", "טבליות"),
    ("Betaloc", "Metoprolol", "טבליות"),
    ("Metoprolol", "Metoprolol", "טבליות"),
    ("Atenolol", "Atenolol", "טבליות"),
    ("Carvedilol", "Carvedilol", "טבליות"),
    ("Norvasc", "Amlodipine", "טבליות"),
    ("Amlopin", "Amlodipine", "טבליות"),
    ("Amlodipine", "Amlodipine", "טבליות"),
    ("Felodipine", "Felodipine", "טבליות"),
    ("Nifedipine", "Nifedipine", "טבליות"),
    ("Verapamil", "Verapamil", "טבליות"),
    ("Diltiazem", "Diltiazem", "טבליות"),
    ("Doxazosin", "Doxazosin", "טבליות"),
    ("Moxonidine", "Moxonidine", "טבליות"),
    ("Clonidine", "Clonidine", "טבליות"),
    ("Methyldopa", "Methyldopa", "טבליות"),
    ("Hydralazine", "Hydralazine", "טבליות"),
    ("Nitroglycerin", "Nitroglycerin", "תת-לשוני / מדבקה"),
    ("Isorind", "Isosorbide Dinitrate", "טבליות"),

    # ═══════════════════════════════════════════════════
    # לב — אי ספיקה / הפרעות קצב
    # ═══════════════════════════════════════════════════
    ("Digoxin", "Digoxin", "טבליות"),
    ("Lanoxin", "Digoxin", "טבליות"),
    ("Amiodarone", "Amiodarone", "טבליות"),
    ("Cordarone", "Amiodarone", "טבליות"),
    ("Entresto", "Sacubitril + Valsartan", "טבליות"),
    ("Coreg", "Carvedilol", "טבליות"),
    ("Inspra", "Eplerenone", "טבליות"),
    ("Veroshpiron", "Spironolactone", "טבליות"),
    ("Ivabradine", "Ivabradine", "טבליות"),
    ("Procoralan", "Ivabradine", "טבליות"),
    ("Sotalol", "Sotalol", "טבליות"),
    ("Flecainide", "Flecainide", "טבליות"),
    ("Propafenone", "Propafenone", "טבליות"),
    ("Tambocor", "Flecainide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # משתנים
    # ═══════════════════════════════════════════════════
    ("Lasix", "Furosemide", "טבליות"),
    ("Furosemide", "Furosemide", "טבליות"),
    ("Aldactone", "Spironolactone", "טבליות"),
    ("Spironolactone", "Spironolactone", "טבליות"),
    ("Moduretic", "Amiloride + Hydrochlorothiazide", "טבליות"),
    ("Hydrochlorothiazide", "Hydrochlorothiazide", "טבליות"),
    ("Indapamide", "Indapamide", "טבליות"),
    ("Torsemide", "Torsemide", "טבליות"),
    ("Bumetanide", "Bumetanide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוגדי קרישה / אנטי-טסיות
    # ═══════════════════════════════════════════════════
    ("Aspirin Cardio", "Aspirin", "טבליות"),
    ("Aspirin", "Aspirin", "טבליות"),
    ("Plavix", "Clopidogrel", "טבליות"),
    ("Clopidogrel", "Clopidogrel", "טבליות"),
    ("Brilique", "Ticagrelor", "טבליות"),
    ("Ticagrelor", "Ticagrelor", "טבליות"),
    ("Prasugrel", "Prasugrel", "טבליות"),
    ("Effient", "Prasugrel", "טבליות"),
    ("Coumadin", "Warfarin", "טבליות"),
    ("Warfarin", "Warfarin", "טבליות"),
    ("Xarelto", "Rivaroxaban", "טבליות"),
    ("Rivaroxaban", "Rivaroxaban", "טבליות"),
    ("Eliquis", "Apixaban", "טבליות"),
    ("Apixaban", "Apixaban", "טבליות"),
    ("Pradaxa", "Dabigatran", "כמוסות"),
    ("Dabigatran", "Dabigatran", "כמוסות"),
    ("Lixiana", "Edoxaban", "טבליות"),
    ("Heparin", "Heparin", "זריקה"),
    ("Clexane", "Enoxaparin", "זריקה"),
    ("Enoxaparin", "Enoxaparin", "זריקה"),
    ("Fragmin", "Dalteparin", "זריקה"),
    ("Innohep", "Tinzaparin", "זריקה"),
    ("Dipyridamole", "Dipyridamole", "טבליות"),
    ("Persantin", "Dipyridamole", "טבליות"),

    # ═══════════════════════════════════════════════════
    # כולסטרול / שומנים
    # ═══════════════════════════════════════════════════
    ("Lipitor", "Atorvastatin", "טבליות"),
    ("Atorvastatin", "Atorvastatin", "טבליות"),
    ("Crestor", "Rosuvastatin", "טבליות"),
    ("Rosuvastatin", "Rosuvastatin", "טבליות"),
    ("Zocor", "Simvastatin", "טבליות"),
    ("Simvastatin", "Simvastatin", "טבליות"),
    ("Pravastatin", "Pravastatin", "טבליות"),
    ("Fluvastatin", "Fluvastatin", "כמוסות"),
    ("Pitavastatin", "Pitavastatin", "טבליות"),
    ("Ezetimibe", "Ezetimibe", "טבליות"),
    ("Ezetrol", "Ezetimibe", "טבליות"),
    ("Inegy", "Ezetimibe + Simvastatin", "טבליות"),
    ("Repatha", "Evolocumab", "זריקה"),
    ("Praluent", "Alirocumab", "זריקה"),
    ("Fenofibrate", "Fenofibrate", "טבליות"),
    ("Lipanthyl", "Fenofibrate", "טבליות"),
    ("Gemfibrozil", "Gemfibrozil", "טבליות"),
    ("Omega-3", "Omega-3 Fatty Acids", "כמוסות"),
    ("Omacor", "Omega-3", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # סוכרת
    # ═══════════════════════════════════════════════════
    ("Glucophage", "Metformin", "טבליות"),
    ("Metformin", "Metformin", "טבליות"),
    ("Januvia", "Sitagliptin", "טבליות"),
    ("Sitagliptin", "Sitagliptin", "טבליות"),
    ("Trajenta", "Linagliptin", "טבליות"),
    ("Galvus", "Vildagliptin", "טבליות"),
    ("Onglyza", "Saxagliptin", "טבליות"),
    ("Jardiance", "Empagliflozin", "טבליות"),
    ("Empagliflozin", "Empagliflozin", "טבליות"),
    ("Forxiga", "Dapagliflozin", "טבליות"),
    ("Dapagliflozin", "Dapagliflozin", "טבליות"),
    ("Invokana", "Canagliflozin", "טבליות"),
    ("Ozempic", "Semaglutide", "זריקה"),
    ("Semaglutide", "Semaglutide", "זריקה / טבליות"),
    ("Rybelsus", "Semaglutide", "טבליות"),
    ("Victoza", "Liraglutide", "זריקה"),
    ("Liraglutide", "Liraglutide", "זריקה"),
    ("Trulicity", "Dulaglutide", "זריקה"),
    ("Byetta", "Exenatide", "זריקה"),
    ("Toujeo", "Insulin Glargine U300", "זריקה"),
    ("Lantus", "Insulin Glargine", "זריקה"),
    ("Basaglar", "Insulin Glargine", "זריקה"),
    ("Tresiba", "Insulin Degludec", "זריקה"),
    ("Levemir", "Insulin Detemir", "זריקה"),
    ("Novorapid", "Insulin Aspart", "זריקה"),
    ("Humalog", "Insulin Lispro", "זריקה"),
    ("Apidra", "Insulin Glulisine", "זריקה"),
    ("Humulin R", "Regular Insulin", "זריקה"),
    ("Humulin N", "NPH Insulin", "זריקה"),
    ("Mixtard", "Biphasic Insulin", "זריקה"),
    ("Amaryl", "Glimepiride", "טבליות"),
    ("Glimepiride", "Glimepiride", "טבליות"),
    ("Glipizide", "Glipizide", "טבליות"),
    ("Gliclazide", "Gliclazide", "טבליות"),
    ("Pioglitazone", "Pioglitazone", "טבליות"),
    ("Acarbose", "Acarbose", "טבליות"),
    ("Repaglinide", "Repaglinide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # בלוטת תריס
    # ═══════════════════════════════════════════════════
    ("Eltroxin", "Levothyroxine", "טבליות"),
    ("Euthyrox", "Levothyroxine", "טבליות"),
    ("Levothyroxine", "Levothyroxine", "טבליות"),
    ("Synthroid", "Levothyroxine", "טבליות"),
    ("Propylthiouracil", "Propylthiouracil", "טבליות"),
    ("Carbimazole", "Carbimazole", "טבליות"),
    ("Thyroblock", "Potassium Iodide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — אפילפסיה
    # ═══════════════════════════════════════════════════
    ("Tegretol", "Carbamazepine", "טבליות"),
    ("Carbamazepine", "Carbamazepine", "טבליות"),
    ("Depakine", "Valproic Acid", "טבליות"),
    ("Valproic Acid", "Valproic Acid", "טבליות"),
    ("Lamictal", "Lamotrigine", "טבליות"),
    ("Lamotrigine", "Lamotrigine", "טבליות"),
    ("Keppra", "Levetiracetam", "טבליות"),
    ("Levetiracetam", "Levetiracetam", "טבליות"),
    ("Topamax", "Topiramate", "כמוסות"),
    ("Topiramate", "Topiramate", "טבליות"),
    ("Phenobarbital", "Phenobarbital", "טבליות"),
    ("Luminal", "Phenobarbital", "טבליות"),
    ("Phenytoin", "Phenytoin", "כמוסות"),
    ("Dilantin", "Phenytoin", "כמוסות"),
    ("Oxcarbazepine", "Oxcarbazepine", "טבליות"),
    ("Trileptal", "Oxcarbazepine", "טבליות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Lyrica", "Pregabalin", "כמוסות"),
    ("Briviact", "Brivaracetam", "טבליות"),
    ("Vimpat", "Lacosamide", "טבליות"),
    ("Fycompa", "Perampanel", "טבליות"),
    ("Epidyolex", "Cannabidiol", "תמיסה"),
    ("Rivotril", "Clonazepam", "טבליות"),
    ("Clonazepam", "Clonazepam", "טבליות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — פרקינסון
    # ═══════════════════════════════════════════════════
    ("Madopar", "Levodopa + Benserazide", "טבליות / כמוסות"),
    ("Sinemet", "Levodopa + Carbidopa", "טבליות"),
    ("Levodopa", "Levodopa", "טבליות"),
    ("Stalevo", "Levodopa + Carbidopa + Entacapone", "טבליות"),
    ("Requip", "Ropinirole", "טבליות"),
    ("Mirapex", "Pramipexole", "טבליות"),
    ("Neupro", "Rotigotine", "מדבקה"),
    ("Azilect", "Rasagiline", "טבליות"),
    ("Rasagiline", "Rasagiline", "טבליות"),
    ("Selegiline", "Selegiline", "טבליות"),
    ("Comtan", "Entacapone", "טבליות"),
    ("Tasmar", "Tolcapone", "טבליות"),
    ("Amantadine", "Amantadine", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — טרשת נפוצה (MS)
    # ═══════════════════════════════════════════════════
    ("Copaxone", "Glatiramer Acetate", "זריקה"),
    ("Avonex", "Interferon Beta-1a", "זריקה"),
    ("Rebif", "Interferon Beta-1a", "זריקה"),
    ("Betaferon", "Interferon Beta-1b", "זריקה"),
    ("Extavia", "Interferon Beta-1b", "זריקה"),
    ("Tecfidera", "Dimethyl Fumarate", "כמוסות"),
    ("Aubagio", "Teriflunomide", "טבליות"),
    ("Gilenya", "Fingolimod", "כמוסות"),
    ("Mayzent", "Siponimod", "טבליות"),
    ("Kesimpta", "Ofatumumab", "זריקה"),
    ("Ocrevus", "Ocrelizumab", "עירוי"),
    ("Tysabri", "Natalizumab", "עירוי"),
    ("Lemtrada", "Alemtuzumab", "עירוי"),
    ("Ponvory", "Ponesimod", "טבליות"),
    ("Zeposia", "Ozanimod", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # נוירולוגיה — דמנציה / אלצהיימר
    # ═══════════════════════════════════════════════════
    ("Aricept", "Donepezil", "טבליות"),
    ("Donepezil", "Donepezil", "טבליות"),
    ("Exelon", "Rivastigmine", "טבליות / מדבקה"),
    ("Rivastigmine", "Rivastigmine", "כמוסות / מדבקה"),
    ("Reminyl", "Galantamine", "כמוסות"),
    ("Galantamine", "Galantamine", "כמוסות"),
    ("Ebixa", "Memantine", "טבליות / תמיסה"),
    ("Memantine", "Memantine", "טבליות"),

    # ═══════════════════════════════════════════════════
    # פסיכיאטריה — דיכאון / חרדה
    # ═══════════════════════════════════════════════════
    ("Cipralex", "Escitalopram", "טבליות"),
    ("Escitalopram", "Escitalopram", "טבליות"),
    ("Prozac", "Fluoxetine", "כמוסות"),
    ("Fluoxetine", "Fluoxetine", "כמוסות"),
    ("Zoloft", "Sertraline", "טבליות"),
    ("Sertraline", "Sertraline", "טבליות"),
    ("Effexor", "Venlafaxine", "כמוסות"),
    ("Venlafaxine", "Venlafaxine", "כמוסות"),
    ("Cymbalta", "Duloxetine", "כמוסות"),
    ("Duloxetine", "Duloxetine", "כמוסות"),
    ("Remeron", "Mirtazapine", "טבליות"),
    ("Mirtazapine", "Mirtazapine", "טבליות"),
    ("Paroxetine", "Paroxetine", "טבליות"),
    ("Citalopram", "Citalopram", "טבליות"),
    ("Fluvoxamine", "Fluvoxamine", "טבליות"),
    ("Anafranil", "Clomipramine", "טבליות"),
    ("Clomipramine", "Clomipramine", "טבליות"),
    ("Amitriptyline", "Amitriptyline", "טבליות"),
    ("Nortriptyline", "Nortriptyline", "טבליות"),
    ("Bupropion", "Bupropion", "טבליות"),
    ("Wellbutrin", "Bupropion", "טבליות"),
    ("Valdoxan", "Agomelatine", "טבליות"),
    ("Xanax", "Alprazolam", "טבליות"),
    ("Alprazolam", "Alprazolam", "טבליות"),
    ("Valium", "Diazepam", "טבליות"),
    ("Diazepam", "Diazepam", "טבליות"),
    ("Lorazepam", "Lorazepam", "טבליות"),
    ("Lorivan", "Lorazepam", "טבליות"),
    ("Buspirone", "Buspirone", "טבליות"),
    ("Pregabalin", "Pregabalin", "כמוסות"),
    ("Stilnox", "Zolpidem", "טבליות"),
    ("Zolpidem", "Zolpidem", "טבליות"),
    ("Imovane", "Zopiclone", "טבליות"),

    # ═══════════════════════════════════════════════════
    # פסיכיאטריה — אנטי-פסיכוטיים / מייצבי מצב רוח
    # ═══════════════════════════════════════════════════
    ("Risperdal", "Risperidone", "טבליות"),
    ("Risperidone", "Risperidone", "טבליות"),
    ("Zyprexa", "Olanzapine", "טבליות"),
    ("Olanzapine", "Olanzapine", "טבליות"),
    ("Seroquel", "Quetiapine", "טבליות"),
    ("Quetiapine", "Quetiapine", "טבליות"),
    ("Abilify", "Aripiprazole", "טבליות"),
    ("Aripiprazole", "Aripiprazole", "טבליות"),
    ("Clozaril", "Clozapine", "טבליות"),
    ("Clozapine", "Clozapine", "טבליות"),
    ("Haldol", "Haloperidol", "טבליות / זריקה"),
    ("Haloperidol", "Haloperidol", "טבליות"),
    ("Amisulpride", "Amisulpride", "טבליות"),
    ("Lithium", "Lithium Carbonate", "טבליות"),
    ("Camcolit", "Lithium Carbonate", "טבליות"),
    ("Depakote", "Valproate Semisodium", "טבליות"),
    ("Lamictal", "Lamotrigine", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ADHD
    # ═══════════════════════════════════════════════════
    ("Ritalin", "Methylphenidate", "טבליות"),
    ("Methylphenidate", "Methylphenidate", "טבליות"),
    ("Concerta", "Methylphenidate ER", "טבליות"),
    ("Medikinet", "Methylphenidate", "כמוסות"),
    ("Adderall", "Amphetamine Salts", "טבליות"),
    ("Strattera", "Atomoxetine", "כמוסות"),
    ("Atomoxetine", "Atomoxetine", "כמוסות"),
    ("Intuniv", "Guanfacine ER", "טבליות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — כימותרפיה קלאסית
    # ═══════════════════════════════════════════════════
    ("Cyclophosphamide", "Cyclophosphamide", "טבליות / זריקה"),
    ("Methotrexate", "Methotrexate", "טבליות / זריקה"),
    ("Fluorouracil", "5-Fluorouracil (5-FU)", "זריקה"),
    ("Capecitabine", "Capecitabine", "טבליות"),
    ("Xeloda", "Capecitabine", "טבליות"),
    ("Doxorubicin", "Doxorubicin", "זריקה"),
    ("Adriamycin", "Doxorubicin", "זריקה"),
    ("Epirubicin", "Epirubicin", "זריקה"),
    ("Paclitaxel", "Paclitaxel", "זריקה"),
    ("Taxol", "Paclitaxel", "זריקה"),
    ("Docetaxel", "Docetaxel", "זריקה"),
    ("Taxotere", "Docetaxel", "זריקה"),
    ("Carboplatin", "Carboplatin", "זריקה"),
    ("Cisplatin", "Cisplatin", "זריקה"),
    ("Oxaliplatin", "Oxaliplatin", "זריקה"),
    ("Eloxatin", "Oxaliplatin", "זריקה"),
    ("Gemcitabine", "Gemcitabine", "זריקה"),
    ("Gemzar", "Gemcitabine", "זריקה"),
    ("Vinorelbine", "Vinorelbine", "טבליות / זריקה"),
    ("Irinotecan", "Irinotecan", "זריקה"),
    ("Etoposide", "Etoposide", "כמוסות / זריקה"),
    ("Pemetrexed", "Pemetrexed", "זריקה"),
    ("Alimta", "Pemetrexed", "זריקה"),
    ("Melphalan", "Melphalan", "טבליות"),
    ("Chlorambucil", "Chlorambucil", "טבליות"),
    ("Bleomycin", "Bleomycin", "זריקה"),
    ("Vincristine", "Vincristine", "זריקה"),
    ("Cytarabine", "Cytarabine (Ara-C)", "זריקה"),
    ("Dacarbazine", "Dacarbazine", "זריקה"),
    ("Temozolomide", "Temozolomide", "כמוסות"),
    ("Temodal", "Temozolomide", "כמוסות"),
    ("Hydroxymethylglutaryl", "Hydroxyurea", "כמוסות"),
    ("Hydroxyurea", "Hydroxyurea", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — טיפול ממוקד (Targeted Therapy)
    # ═══════════════════════════════════════════════════
    ("Herceptin", "Trastuzumab", "עירוי"),
    ("Trastuzumab", "Trastuzumab", "עירוי"),
    ("Kadcyla", "Trastuzumab emtansine (T-DM1)", "עירוי"),
    ("Enhertu", "Trastuzumab deruxtecan", "עירוי"),
    ("Perjeta", "Pertuzumab", "עירוי"),
    ("Avastin", "Bevacizumab", "עירוי"),
    ("Bevacizumab", "Bevacizumab", "עירוי"),
    ("Erbitux", "Cetuximab", "עירוי"),
    ("Vectibix", "Panitumumab", "עירוי"),
    ("Gleevec", "Imatinib", "טבליות"),
    ("Imatinib", "Imatinib", "טבליות"),
    ("Tasigna", "Nilotinib", "כמוסות"),
    ("Sprycel", "Dasatinib", "טבליות"),
    ("Bosulif", "Bosutinib", "טבליות"),
    ("Iclusig", "Ponatinib", "טבליות"),
    ("Tarceva", "Erlotinib", "טבליות"),
    ("Iressa", "Gefitinib", "טבליות"),
    ("Gilotrif", "Afatinib", "טבליות"),
    ("Tagrisso", "Osimertinib", "טבליות"),
    ("Xalkori", "Crizotinib", "כמוסות"),
    ("Alecensa", "Alectinib", "כמוסות"),
    ("Lorbrena", "Lorlatinib", "טבליות"),
    ("Zelboraf", "Vemurafenib", "טבליות"),
    ("Tafinlar", "Dabrafenib", "כמוסות"),
    ("Mekinist", "Trametinib", "טבליות"),
    ("Cotellic", "Cobimetinib", "טבליות"),
    ("Ibrance", "Palbociclib", "כמוסות"),
    ("Kisqali", "Ribociclib", "טבליות"),
    ("Verzenio", "Abemaciclib", "טבליות"),
    ("Lynparza", "Olaparib", "טבליות"),
    ("Zejula", "Niraparib", "כמוסות"),
    ("Rubraca", "Rucaparib", "טבליות"),
    ("Imbruvica", "Ibrutinib", "כמוסות"),
    ("Calquence", "Acalabrutinib", "כמוסות"),
    ("Brukinsa", "Zanubrutinib", "כמוסות"),
    ("Venclexta", "Venetoclax", "טבליות"),
    ("Zytiga", "Abiraterone", "טבליות"),
    ("Xtandi", "Enzalutamide", "כמוסות"),
    ("Nubeqa", "Darolutamide", "טבליות"),
    ("Erleada", "Apalutamide", "טבליות"),
    ("Nexavar", "Sorafenib", "טבליות"),
    ("Sutent", "Sunitinib", "כמוסות"),
    ("Votrient", "Pazopanib", "טבליות"),
    ("Inlyta", "Axitinib", "טבליות"),
    ("Cabometyx", "Cabozantinib", "טבליות"),
    ("Lenvima", "Lenvatinib", "כמוסות"),
    ("Stivarga", "Regorafenib", "טבליות"),
    ("Revlimid", "Lenalidomide", "כמוסות"),
    ("Velcade", "Bortezomib", "זריקה"),
    ("Kyprolis", "Carfilzomib", "עירוי"),
    ("Ninlaro", "Ixazomib", "כמוסות"),
    ("Darzalex", "Daratumumab", "עירוי"),
    ("Pomalyst", "Pomalidomide", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — אימונותרפיה
    # ═══════════════════════════════════════════════════
    ("Keytruda", "Pembrolizumab", "עירוי"),
    ("Pembrolizumab", "Pembrolizumab", "עירוי"),
    ("Opdivo", "Nivolumab", "עירוי"),
    ("Nivolumab", "Nivolumab", "עירוי"),
    ("Tecentriq", "Atezolizumab", "עירוי"),
    ("Imfinzi", "Durvalumab", "עירוי"),
    ("Bavencio", "Avelumab", "עירוי"),
    ("Yervoy", "Ipilimumab", "עירוי"),
    ("Ipilimumab", "Ipilimumab", "עירוי"),
    ("Libtayo", "Cemiplimab", "עירוי"),

    # ═══════════════════════════════════════════════════
    # אונקולוגיה — הורמונלי (שד / ערמונית)
    # ═══════════════════════════════════════════════════
    ("Tamoxifen", "Tamoxifen", "טבליות"),
    ("Nolvadex", "Tamoxifen", "טבליות"),
    ("Femara", "Letrozole", "טבליות"),
    ("Letrozole", "Letrozole", "טבליות"),
    ("Arimidex", "Anastrozole", "טבליות"),
    ("Anastrozole", "Anastrozole", "טבליות"),
    ("Aromasin", "Exemestane", "טבליות"),
    ("Faslodex", "Fulvestrant", "זריקה"),
    ("Lupron", "Leuprolide", "זריקה"),
    ("Zoladex", "Goserelin", "זריקה"),
    ("Decapeptyl", "Triptorelin", "זריקה"),
    ("Firmagon", "Degarelix", "זריקה"),
    ("Casodex", "Bicalutamide", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ראומטולוגיה / מחלות אוטואימוניות
    # ═══════════════════════════════════════════════════
    ("Methotrexate", "Methotrexate", "טבליות / זריקה"),
    ("Plaquenil", "Hydroxychloroquine", "טבליות"),
    ("Hydroxychloroquine", "Hydroxychloroquine", "טבליות"),
    ("Sulfasalazine", "Sulfasalazine", "טבליות"),
    ("Azulfidine", "Sulfasalazine", "טבליות"),
    ("Leflunomide", "Leflunomide", "טבליות"),
    ("Arava", "Leflunomide", "טבליות"),
    ("Prednisone", "Prednisone", "טבליות"),
    ("Prednisolone", "Prednisolone", "טבליות"),
    ("Methylprednisolone", "Methylprednisolone", "טבליות / זריקה"),
    ("Medrol", "Methylprednisolone", "טבליות"),
    ("Humira", "Adalimumab", "זריקה"),
    ("Adalimumab", "Adalimumab", "זריקה"),
    ("Enbrel", "Etanercept", "זריקה"),
    ("Etanercept", "Etanercept", "זריקה"),
    ("Remicade", "Infliximab", "עירוי"),
    ("Infliximab", "Infliximab", "עירוי"),
    ("Simponi", "Golimumab", "זריקה"),
    ("Cimzia", "Certolizumab Pegol", "זריקה"),
    ("Orencia", "Abatacept", "זריקה / עירוי"),
    ("Actemra", "Tocilizumab", "עירוי / זריקה"),
    ("Kevzara", "Sarilumab", "זריקה"),
    ("Rinvoq", "Upadacitinib", "טבליות"),
    ("Xeljanz", "Tofacitinib", "טבליות"),
    ("Olumiant", "Baricitinib", "טבליות"),
    ("Cosentyx", "Secukinumab", "זריקה"),
    ("Taltz", "Ixekizumab", "זריקה"),
    ("Tremfya", "Guselkumab", "זריקה"),
    ("Stelara", "Ustekinumab", "זריקה / עירוי"),
    ("Skyrizi", "Risankizumab", "זריקה"),
    ("Rituximab", "Rituximab", "עירוי"),
    ("MabThera", "Rituximab", "עירוי"),
    ("Benlysta", "Belimumab", "עירוי / זריקה"),
    ("Mycophenolate", "Mycophenolate Mofetil", "כמוסות"),
    ("CellCept", "Mycophenolate Mofetil", "כמוסות"),
    ("Cyclosporine", "Cyclosporine", "כמוסות"),
    ("Neoral", "Cyclosporine", "כמוסות"),
    ("Tacrolimus", "Tacrolimus", "כמוסות"),
    ("Prograf", "Tacrolimus", "כמוסות"),
    ("Azathioprine", "Azathioprine", "טבליות"),
    ("Imuran", "Azathioprine", "טבליות"),
    ("Colchicine", "Colchicine", "טבליות"),
    ("Allopurinol", "Allopurinol", "טבליות"),
    ("Zyloric", "Allopurinol", "טבליות"),
    ("Febuxostat", "Febuxostat", "טבליות"),
    ("Adenuric", "Febuxostat", "טבליות"),

    # ═══════════════════════════════════════════════════
    # ריאות / נשימה
    # ═══════════════════════════════════════════════════
    ("Ventolin", "Salbutamol", "אינהלר"),
    ("Salbutamol", "Salbutamol", "אינהלר"),
    ("Bricanyl", "Terbutaline", "אינהלר"),
    ("Formoterol", "Formoterol", "אינהלר"),
    ("Salmeterol", "Salmeterol", "אינהלר"),
    ("Flixotide", "Fluticasone", "אינהלר"),
    ("Pulmicort", "Budesonide", "אינהלר"),
    ("Qvar", "Beclomethasone", "אינהלר"),
    ("Alvesco", "Ciclesonide", "אינהלר"),
    ("Symbicort", "Budesonide + Formoterol", "אינהלר"),
    ("Seretide", "Salmeterol + Fluticasone", "אינהלר"),
    ("Relvar", "Vilanterol + Fluticasone", "אינהלר"),
    ("Trelegy", "FF + Vilanterol + UMEC", "אינהלר"),
    ("Spiriva", "Tiotropium", "אינהלר"),
    ("Tiotropium", "Tiotropium", "אינהלר"),
    ("Incruse", "Umeclidinium", "אינהלר"),
    ("Bretaris", "Aclidinium", "אינהלר"),
    ("Atrovent", "Ipratropium", "אינהלר"),
    ("Ipratropium", "Ipratropium", "אינהלר"),
    ("Daliresp", "Roflumilast", "טבליות"),
    ("Zithromax", "Azithromycin", "טבליות"),
    ("Ofev", "Nintedanib", "כמוסות"),
    ("Esbriet", "Pirfenidone", "כמוסות"),
    ("Dupixent", "Dupilumab", "זריקה"),
    ("Nucala", "Mepolizumab", "זריקה"),
    ("Fasenra", "Benralizumab", "זריקה"),
    ("Cinqair", "Reslizumab", "עירוי"),
    ("Xolair", "Omalizumab", "זריקה"),
    ("Montelukast", "Montelukast", "טבליות"),
    ("Singulair", "Montelukast", "טבליות"),
    ("Theophylline", "Theophylline", "טבליות"),

    # ═══════════════════════════════════════════════════
    # גסטרואנטרולוגיה
    # ═══════════════════════════════════════════════════
    ("Losec", "Omeprazole", "כמוסות"),
    ("Omepradex", "Omeprazole", "כמוסות"),
    ("Omeprazole", "Omeprazole", "כמוסות"),
    ("Nexium", "Esomeprazole", "טבליות"),
    ("Esomeprazole", "Esomeprazole", "טבליות"),
    ("Controloc", "Pantoprazole", "טבליות"),
    ("Pantoprazole", "Pantoprazole", "טבליות"),
    ("Lansoprazole", "Lansoprazole", "כמוסות"),
    ("Rabeprazole", "Rabeprazole", "טבליות"),
    ("Zantac", "Ranitidine", "טבליות"),
    ("Motilium", "Domperidone", "טבליות"),
    ("Primpiran", "Metoclopramide", "טבליות"),
    ("Metoclopramide", "Metoclopramide", "טבליות"),
    ("Imodium", "Loperamide", "טבליות"),
    ("Loperamide", "Loperamide", "טבליות"),
    ("Dulcolax", "Bisacodyl", "טבליות / סופוזיטוריה"),
    ("Lactulose", "Lactulose", "תמיסה"),
    ("Macrogol", "Polyethylene Glycol", "אבקה"),
    ("Forlax", "Macrogol", "אבקה"),
    ("Buscopan", "Hyoscine Butylbromide", "טבליות"),
    ("Mezavant", "Mesalazine", "טבליות"),
    ("Pentasa", "Mesalazine", "טבליות / כמוסות"),
    ("Asacol", "Mesalazine", "טבליות"),
    ("Mesalazine", "Mesalazine", "טבליות"),
    ("Budenofalk", "Budesonide", "כמוסות"),
    ("Remicade", "Infliximab", "עירוי"),
    ("Entyvio", "Vedolizumab", "עירוי"),
    ("Stelara", "Ustekinumab", "עירוי"),
    ("Ursofalk", "Ursodeoxycholic Acid", "כמוסות"),
    ("Ursodiol", "Ursodeoxycholic Acid", "כמוסות"),
    ("Rifaximin", "Rifaximin", "טבליות"),
    ("Xifaxan", "Rifaximin", "טבליות"),
    ("Ondansetron", "Ondansetron", "טבליות"),
    ("Zofran", "Ondansetron", "טבליות"),
    ("Aprepitant", "Aprepitant", "כמוסות"),
    ("Emend", "Aprepitant", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # כליות / נפרולוגיה
    # ═══════════════════════════════════════════════════
    ("Erythropoietin", "Erythropoietin (EPO)", "זריקה"),
    ("Aranesp", "Darbepoetin Alfa", "זריקה"),
    ("Mircera", "Methoxy PEG-Epoetin Beta", "זריקה"),
    ("Renagel", "Sevelamer", "טבליות"),
    ("Sevelamer", "Sevelamer", "טבליות"),
    ("Calcium Carbonate", "Calcium Carbonate", "טבליות"),
    ("Paricalcitol", "Paricalcitol", "כמוסות / זריקה"),
    ("Cinacalcet", "Cinacalcet", "טבליות"),
    ("Mimpara", "Cinacalcet", "טבליות"),
    ("Patiromer", "Patiromer", "אבקה"),
    ("Veltassa", "Patiromer", "אבקה"),
    ("Kerendia", "Finerenone", "טבליות"),
    ("Sodium Bicarbonate", "Sodium Bicarbonate", "טבליות"),

    # ═══════════════════════════════════════════════════
    # המטולוגיה
    # ═══════════════════════════════════════════════════
    ("Iron Supplement", "Iron (Ferrous Sulfate)", "טבליות"),
    ("Ferrum Hausmann", "Iron Polymaltose", "טבליות / זריקה"),
    ("Ferinject", "Ferric Carboxymaltose", "עירוי"),
    ("Venofer", "Iron Sucrose", "עירוי"),
    ("Vitamin B12", "Cyanocobalamin", "טבליות / זריקה"),
    ("Folic Acid", "Folic Acid", "טבליות"),
    ("Revlimid", "Lenalidomide", "כמוסות"),
    ("Thalidomide", "Thalidomide", "כמוסות"),
    ("Jakavi", "Ruxolitinib", "טבליות"),
    ("Calquence", "Acalabrutinib", "כמוסות"),
    ("Imbruvica", "Ibrutinib", "כמוסות"),
    ("G-CSF", "Filgrastim", "זריקה"),
    ("Neupogen", "Filgrastim", "זריקה"),
    ("Neulasta", "Pegfilgrastim", "זריקה"),

    # ═══════════════════════════════════════════════════
    # אנטיביוטיקה
    # ═══════════════════════════════════════════════════
    ("Amoxicillin", "Amoxicillin", "כמוסות"),
    ("Augmentin", "Amoxicillin + Clavulanate", "טבליות"),
    ("Amoxicillin + Clavulanate", "Amoxicillin + Clavulanate", "טבליות"),
    ("Azithromycin", "Azithromycin", "טבליות"),
    ("Zithromax", "Azithromycin", "טבליות"),
    ("Klacid", "Clarithromycin", "טבליות"),
    ("Clarithromycin", "Clarithromycin", "טבליות"),
    ("Cipro", "Ciprofloxacin", "טבליות"),
    ("Ciprobay", "Ciprofloxacin", "טבליות"),
    ("Ciprofloxacin", "Ciprofloxacin", "טבליות"),
    ("Levofloxacin", "Levofloxacin", "טבליות"),
    ("Tavanic", "Levofloxacin", "טבליות"),
    ("Moxifloxacin", "Moxifloxacin", "טבליות"),
    ("Avelox", "Moxifloxacin", "טבליות"),
    ("Doxycycline", "Doxycycline", "כמוסות"),
    ("Vibramycin", "Doxycycline", "כמוסות"),
    ("Tetracycline", "Tetracycline", "כמוסות"),
    ("Minocycline", "Minocycline", "כמוסות"),
    ("Trimethoprim-Sulfamethoxazole", "TMP-SMX", "טבליות"),
    ("Bactrim", "TMP-SMX", "טבליות"),
    ("Septrin", "TMP-SMX", "טבליות"),
    ("Metronidazole", "Metronidazole", "טבליות"),
    ("Flagyl", "Metronidazole", "טבליות"),
    ("Clindamycin", "Clindamycin", "כמוסות / זריקה"),
    ("Dalacin C", "Clindamycin", "כמוסות"),
    ("Vancomycin", "Vancomycin", "זריקה"),
    ("Linezolid", "Linezolid", "טבליות / עירוי"),
    ("Zyvox", "Linezolid", "טבליות"),
    ("Rifampicin", "Rifampicin", "כמוסות"),
    ("Isoniazid", "Isoniazid", "טבליות"),
    ("Ethambutol", "Ethambutol", "טבליות"),
    ("Pyrazinamide", "Pyrazinamide", "טבליות"),
    ("Ceftriaxone", "Ceftriaxone", "זריקה"),
    ("Cefuroxime", "Cefuroxime", "טבליות / זריקה"),
    ("Zinnat", "Cefuroxime Axetil", "טבליות"),
    ("Cephalexin", "Cephalexin", "כמוסות"),
    ("Keflex", "Cephalexin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # אנטי-פטרייתי / אנטי-ויראלי
    # ═══════════════════════════════════════════════════
    ("Fluconazole", "Fluconazole", "כמוסות"),
    ("Diflucan", "Fluconazole", "כמוסות"),
    ("Itraconazole", "Itraconazole", "כמוסות"),
    ("Voriconazole", "Voriconazole", "טבליות"),
    ("Acyclovir", "Acyclovir", "טבליות"),
    ("Zovirax", "Acyclovir", "טבליות / משחה"),
    ("Valacyclovir", "Valacyclovir", "טבליות"),
    ("Valtrex", "Valacyclovir", "טבליות"),
    ("Famciclovir", "Famciclovir", "טבליות"),
    ("Oseltamivir", "Oseltamivir", "כמוסות"),
    ("Tamiflu", "Oseltamivir", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # HIV / AIDS
    # ═══════════════════════════════════════════════════
    ("Truvada", "Tenofovir + Emtricitabine", "טבליות"),
    ("Biktarvy", "Bictegravir + FTC + TAF", "טבליות"),
    ("Genvoya", "Elvitegravir combo", "טבליות"),
    ("Triumeq", "DTG + ABC + 3TC", "טבליות"),
    ("Dolutegravir", "Dolutegravir", "טבליות"),
    ("Tivicay", "Dolutegravir", "טבליות"),
    ("Atripla", "EFV + FTC + TDF", "טבליות"),
    ("Raltegravir", "Raltegravir", "טבליות"),
    ("Isentress", "Raltegravir", "טבליות"),

    # ═══════════════════════════════════════════════════
    # אלרגיה / עור
    # ═══════════════════════════════════════════════════
    ("Clarityn", "Loratadine", "טבליות"),
    ("Loratadine", "Loratadine", "טבליות"),
    ("Zyrtec", "Cetirizine", "טבליות"),
    ("Cetirizine", "Cetirizine", "טבליות"),
    ("Aerius", "Desloratadine", "טבליות"),
    ("Desloratadine", "Desloratadine", "טבליות"),
    ("Allegra", "Fexofenadine", "טבליות"),
    ("Fexofenadine", "Fexofenadine", "טבליות"),
    ("Hydrocortisone", "Hydrocortisone", "משחה / קרם"),
    ("Betamethasone", "Betamethasone", "משחה"),
    ("Clobetasol", "Clobetasol", "משחה"),
    ("Dupixent", "Dupilumab", "זריקה"),
    ("Skyrizi", "Risankizumab", "זריקה"),
    ("Tremfya", "Guselkumab", "זריקה"),
    ("Cosentyx", "Secukinumab", "זריקה"),
    ("Taltz", "Ixekizumab", "זריקה"),
    ("Humira", "Adalimumab", "זריקה"),
    ("Isotretinoin", "Isotretinoin", "כמוסות"),
    ("Roaccutane", "Isotretinoin", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # עיניים
    # ═══════════════════════════════════════════════════
    ("Eylea", "Aflibercept", "זריקה תוך-עינית"),
    ("Lucentis", "Ranibizumab", "זריקה תוך-עינית"),
    ("Beovu", "Brolucizumab", "זריקה תוך-עינית"),
    ("Timolol", "Timolol", "טיפות עיניים"),
    ("Xalatan", "Latanoprost", "טיפות עיניים"),
    ("Cosopt", "Dorzolamide + Timolol", "טיפות עיניים"),
    ("Trusopt", "Dorzolamide", "טיפות עיניים"),
    ("Lumigan", "Bimatoprost", "טיפות עיניים"),

    # ═══════════════════════════════════════════════════
    # אוסטאופורוזיס
    # ═══════════════════════════════════════════════════
    ("Fosamax", "Alendronate", "טבליות"),
    ("Alendronate", "Alendronate", "טבליות"),
    ("Bonviva", "Ibandronate", "טבליות / זריקה"),
    ("Actonel", "Risedronate", "טבליות"),
    ("Prolia", "Denosumab", "זריקה"),
    ("Evenity", "Romosozumab", "זריקה"),
    ("Forteo", "Teriparatide", "זריקה"),
    ("Calcium D3", "Calcium + Vitamin D3", "טבליות"),
    ("Vitamin D3", "Cholecalciferol", "טיפות / טבליות"),

    # ═══════════════════════════════════════════════════
    # אנדוקרינולוגיה — שונות
    # ═══════════════════════════════════════════════════
    ("Hydrocortisone", "Hydrocortisone", "טבליות / זריקה"),
    ("Dexamethasone", "Dexamethasone", "טבליות / זריקה"),
    ("Florinef", "Fludrocortisone", "טבליות"),
    ("Somatropin", "Somatropin (GH)", "זריקה"),
    ("Octreotide", "Octreotide", "זריקה"),
    ("Sandostatin", "Octreotide", "זריקה"),
    ("Testosterone", "Testosterone", "ג'ל / זריקה"),
    ("Androgel", "Testosterone", "ג'ל"),
    ("Estradiol", "Estradiol", "טבליות / מדבקה"),
    ("Progesterone", "Progesterone", "כמוסות / ג'ל"),
    ("Utrogestan", "Progesterone", "כמוסות"),

    # ═══════════════════════════════════════════════════
    # שתן / פרוסטטה
    # ═══════════════════════════════════════════════════
    ("Omnic", "Tamsulosin", "כמוסות"),
    ("Tamsulosin", "Tamsulosin", "כמוסות"),
    ("Alfuzosin", "Alfuzosin", "טבליות"),
    ("Xatral", "Alfuzosin", "טבליות"),
    ("Finasteride", "Finasteride", "טבליות"),
    ("Proscar", "Finasteride 5mg", "טבליות"),
    ("Avodart", "Dutasteride", "כמוסות"),
    ("Dutasteride", "Dutasteride", "כמוסות"),
    ("Detrusitol", "Tolterodine", "כמוסות"),
    ("Vesicare", "Solifenacin", "טבליות"),
    ("Toviaz", "Fesoterodine", "טבליות"),
    ("Myrbetriq", "Mirabegron", "טבליות"),

    # ═══════════════════════════════════════════════════
    # מיגרנה
    # ═══════════════════════════════════════════════════
    ("Imigran", "Sumatriptan", "טבליות"),
    ("Sumatriptan", "Sumatriptan", "טבליות"),
    ("Zomig", "Zolmitriptan", "טבליות"),
    ("Maxalt", "Rizatriptan", "טבליות"),
    ("Relpax", "Eletriptan", "טבליות"),
    ("Nurtec", "Rimegepant", "טבליות"),
    ("Ubrelvy", "Ubrogepant", "טבליות"),
    ("Aimovig", "Erenumab", "זריקה"),
    ("Ajovy", "Fremanezumab", "זריקה"),
    ("Emgality", "Galcanezumab", "זריקה"),
    ("Vyepti", "Eptinezumab", "עירוי"),
    ("Topamax", "Topiramate", "טבליות"),
    ("Propranolol", "Propranolol", "טבליות"),
    ("Amitriptyline", "Amitriptyline", "טבליות"),
    ("Botox", "Botulinum Toxin A", "זריקה"),

    # ═══════════════════════════════════════════════════
    # ויטמינים / תוספים
    # ═══════════════════════════════════════════════════
    ("Vitamin B12", "Cyanocobalamin", "טבליות / זריקה"),
    ("Folic Acid", "Folic Acid", "טבליות"),
    ("Vitamin D3", "Cholecalciferol", "טיפות / טבליות"),
    ("Vitamin C", "Ascorbic Acid", "טבליות"),
    ("Vitamin K", "Phytomenadione", "טבליות"),
    ("Magnesium", "Magnesium", "טבליות"),
    ("Potassium Chloride", "Potassium Chloride", "טבליות"),
    ("Slow-K", "Potassium Chloride", "טבליות"),
    ("Iron Supplement", "Ferrous Sulfate", "טבליות"),
    ("Zinc", "Zinc", "טבליות"),

    # ═══════════════════════════════════════════════════
    # שמירת הריון /妇科
    # ═══════════════════════════════════════════════════
    ("Gestone", "Progesterone", "זריקה"),
    ("Crinone", "Progesterone", "ג'ל"),
    ("Clomid", "Clomiphene", "טבליות"),
    ("Puregon", "Follitropin Beta", "זריקה"),
    ("Gonal-F", "Follitropin Alfa", "זריקה"),
    ("Pregnyl", "hCG", "זריקה"),
    ("Diphereline", "Triptorelin", "זריקה"),
    ("Lupron", "Leuprolide", "זריקה"),
]
